### ISSUE TITLE
Adapt to Search Guard

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-docker#101]
We need to include Search Guard as part of the Docker deployment.

Related: https://github.com/wazuh/wazuh-kubernetes/issues/16

**Comment by LuisGi93** [comment]
Hi team,
It was possible to replicate the demo scenario that was done in the virtual machines environment but this time in a docker environment. After this,  the demo settings like the demo certificates and unsafe calls to the search-guard management API were replaced by their secure counterparts. Right now only elasticsearch is using generated certificates. Work is being done so Kibana and Logstash can secure their communication with Elasticsearch. 
Despite this progress testing is needed to be sure that search-guard is being correctly used and that is worked has expected.

**Comment by LuisGi93** [comment]
Hi team,
First I'm going to resume what I did today then I going to sum up what have been done until now and in which state is this project.

Today I was finally able to install Kibana outside the dockerfile. I included the installation step in a script that is called from the entrypoint.sh script so now it is posible to optionally install searchguard if in the dockercompose we set the SEARCHGUARD variable to enable:
```
 48   ┊ environment:
 49   ┊ ┊ - SEARCHGUARD=enabled

```

I have been also researching how to set up the searchguard installation with logstash. Right now we don't have an entrypoint or any script that is called when the containers is executed, so we need to add something to edit  01-wazuh.conf to enable the encryption that searchguard provides:

```output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
        document_type => "wazuh"
#       user =>  logstash
#       password =>  logstash
#       logstash_elasticsearch_ssl =>  true
#       ssl_certificate_verification =>  true
#       cacert => /usr/share/logstash/config/root-ca.pem
    }
}

```

Finally I'm going to list what have been done so far:
-  The searchguard plugin can be optionally installed at the elasticsearch and at the kibana containers.
-  An initial configuration [has been set up](https://github.com/wazuh/wazuh-docker/blob/wazuh-docker-searchguard/elasticsearch/config/searchguard/sg_roles.yml).
- It is possibe to encrypt the communication between elasticserach, kibana and logstash using a shared CA.

I would, however, like to make a few clarifications on this matter:

- Right now there is not possible to enable the encryption at Logstash. Like I said we don't have a script  that is executed when the container is launched to uncomment the lines that enable the encryption, however is posible to edit these lines manually when building the image for enabling the encription.
-  More testing is needed if we set the environment variables to not install searchguard, to be sure that our nodes stays as our original release.
- For the installation of searchguard it needs some certificates. To generate this certificates the [searchguard offline-tls-tool](https://docs.search-guard.com/latest/offline-tls-tool) is used and because we share a CA between elastic, kibana an logstash a CA need to be present when the container is executed. Right now the CA is copied using the Dockerfile so  if the CA is not where the Dockerfile expects it the build will fail.
-  The searchguard plugin  at the Kibana node  is installed with the --no-optimize option. More testing is need to be sure that it is correctly installed.
- It need more test of what happens when a container is stopped and executed again to check that it keeps its state and that the scripts that installs searchguard dont "broke" the configuration files.
- A review of the permissions of the certificates generated by searchguard offline-tls-tool is needed.
- Also a review of the permission of the initial roles at the  initial configuration file is needed.

This work it would not have been possible without [our searchguard guide](https://documentation.wazuh.com/current/installation-guide/optional-configurations/searchguard.html])
