### ISSUE TITLE
Unused variables in build-images.sh

### ISSUE THREAD

**Issue by kedras** [wazuh/wazuh-docker#1027]
Are these variables used anywhere at all now? First one is overwritten few line after and the other one seems to not be used at all since the https://github.com/wazuh/wazuh-docker/commit/32b1d88e36cc8cae839333422b1bb0ae8ea35e71. We could get off one curl call.

https://github.com/wazuh/wazuh-docker/blob/69868c0c709602664e26c81b3fe6d4b87f09a671/build-docker-images/build-images.sh#L2
https://github.com/wazuh/wazuh-docker/blob/69868c0c709602664e26c81b3fe6d4b87f09a671/build-docker-images/build-images.sh#L4

**Comment by davidcr01** [comment]
Hello.

Yes, these variables are no longer used anymore. These variables were used in development, and when the code is from production, these variables have the same value.

About the `WAZUH_CURRENT_VERSION`, it is used but defined in other files. So this variable can be removed in the `build_images.sh` file.

This PR removes these variables: https://github.com/wazuh/wazuh-docker/pull/1025. The PR is merged into the 4.6.0 Wazuh version so that the variables will remain until this version.
