### ISSUE TITLE
"Application Not Found" on fresh single-node installation

### ISSUE THREAD

**Issue by GewoonJaap** [wazuh/wazuh-docker#1123]
I freshly installed the single-node  (4.6.0)  Docker Compose. But I keep getting this error.. What am I doing wrong?  I followed this tutorial https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment but doesn't seem to work

![afbeelding](https://github.com/wazuh/wazuh-docker/assets/33700526/9c57f142-6884-46e8-add6-791309af2f09)

**Comment by GewoonJaap** [comment]
When manually browsing to `/app/wazuh/` it seems to work. Somewhere `/app/wz-home/` must be configured as default URL.

**Comment by GewoonJaap** [comment]
Ah then the version is the problem. I used `4.6.0`, however it looks like `4.8.0` isn't available on Dockerhub as of now: https://hub.docker.com/r/wazuh/wazuh-dashboard/tags

**Comment by rauldpm** [comment]
Yes, version 4.8.0 is not officially available yet, we have just published version 4.7.0

I understand that you have modified the deployment to use 4.8.0? Is the deployment correct using version v4.6.0 then?

**Comment by lvillis** [comment]
The stand-alone version uses version 4.9.0, but the image has not been released. I manually changed it to 4.6.0. I encountered the same problem.

> Yes, version 4.8.0 is not officially available yet, we have just published version 4.7.0
> 
> I understand that you have modified the deployment to use 4.8.0? Is the deployment correct using version v4.6.0 then?

**Comment by rauldpm** [comment]
As the repository readme says:

> master branch contains the latest code, be aware of possible bugs on this branch.

Please, do not modify the master branch to make a production deployment, if you want to make a deployment use the latest production tag, which is now v4.7.0, in the case of the issue it would be v4.6.0

The documentation also specifies this, it is already prepared to deploy without making changes in the code (exept possible changes to configuration files according to your needs): 

- https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html

> Clone the Wazuh repository to your system:
> 
> git clone https://github.com/wazuh/wazuh-docker.git -b v4.7.0
> 
> Then enter into the single-node directory to execute all the commands described below within this directory.


The tags can be found in the following section:

![image](https://github.com/wazuh/wazuh-docker/assets/14913942/64f5e47d-e2dc-4336-a646-eba6005b48cd)


It is not necessary to modify the versions of the images, as I said, if you want to deploy a specific version, clone the version tag.

You are mixing versions and branches, each branch/tag corresponds to a version of the product, the tags being the published versions, the rest of the branches (master, 4.8.0, 4.7.1, etc.) are development branches, please read the documentation in order to correctly deploy it.

**Comment by lvillis** [comment]
Thanks for the answer, this worked for me.

**Comment by GewoonJaap** [comment]
Closing this issue now. Wasn't aware that I should use a different branch than master.

**Comment by chhsoe** [comment]
Well, i encountered this problem to because i was dumb. 
I took the master-branch which didnt work, then i changed the version numbers and then encountered this issue. 
Remember to delete the volumes/storage. That worked for me.

**Comment by bmm-alc** [comment]
Hi there,

I just upgraded my k8s setup from 4.7.5 to 4.8.0 (I follow the stable released version) and got hit by the same bug.

**Comment by 7djs7** [comment]
> Hi there,
> 
> I just upgraded my k8s setup from 4.7.5 to 4.8.0 (I follow the stable released version) and got hit by the same bug.
> 
> ```
> k exec --as cluster-admin -ti -n wazuh pods/wazuh-dashboard-5987ff86-7thq2 -- bash
> bash-5.2$ grep app /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml 
> uiSettings.overrides.defaultRoute: /app/wazuh
> bash-5.2$ cat /usr/share/wazuh-dashboard/VERSION
> 4.8.0
> ```
> 
> ```
> k exec --as cluster-admin -ti -n wazuh pods/wazuh-manager-master-0 -- bash
> bash-5.2# /var/ossec/bin/wazuh-control info
> WAZUH_VERSION="v4.8.0"
> WAZUH_REVISION="40812"
> WAZUH_TYPE="server"
> ```
> 
> I manually edited the dashboard configmap and rollout the pod and it fixed the issue but, did I miss any migration step I would overlooked.

Had the same issue. I run wazuh in docker compose and upgraded 4.7.5 to 4.8.0. I had to edit the line `uiSettings.overrides.defaultRoute:/app/wazuh` in 

`/wazuh-docker/single-node/config/wazuh_dashboard/opensearch_dashboards.yml`
 
to the following
 
`uiSettings.overrides.defaultRoute: /app/wz-home`

I then restarted my docker containers and it worked.

**Comment by zakkg3** [comment]
for 4.9.1 also this line changed:

```
plugins.security.nodes_dn:
  - CN=indexer,O=Company,L=California,C=US
 ```

on indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml
