### ISSUE TITLE
Docker Dashboard missing indexer url variable

### ISSUE THREAD

**Issue by wuast94** [wazuh/wazuh-docker#1194]
> Ah sorry, I understand now, yes, you are right, if the `wazuh-manager` uses the `INDEXER_URL` in the environment section, the `wazuh-dashboard` should specify it too, please open an issue about this as it could need internal code changes

as discussed in #1191 the dasboard container missing an Envirement variable to set the indexer url. the indexer url is hardcoded in the container.

the master container has this option

**Comment by vcerenu** [comment]
Hello @wuast94

I was reading the previous issue but what is not clear is that the use of the `INDEXER_URL` variable would be to replace the `opensearch.hosts:` value within the `opensearch_dashboards.yml` file so that it can be parameterized within the container.

The value is currently received when the `config/wazuh_dashboard/opensearch_dashboards.yml` file is mounted to the Wazuh dashboard container:

``` yaml
volumes:
  ...
  - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
```

If you want to configure this value you should modify it within this file.

We know that it is better to have parameters for each value, but for this we should carry out a development on the Wazuh dashboard image that we do not have contemplated within our current roadmap.

If you want to contribute your development on this topic, you are welcome, you can send us your PR and we will analyze it
