### ISSUE TITLE
Wazuh docker image for ELK 6.6.1

### ISSUE THREAD

**Issue by 0x18katyan** [wazuh/wazuh-docker#125]
Is Wazuh 3.8.2-1 compatible with ELK 6.6.1? I have a custom ELK stack running on 6.6.1 for which I intend to use Wazuh. I was formally using ELK stack 6.2.2(same version Filebeat) and Wazuh 3.2.1-1 minus the Wazuh-Kibana-App due to usage of SearchGuard. Now I am shifting to 6.6.1 and was wondering if modifying the DockerFile (Filebeat version) for the Wazuh-Manager image would work as a hack or is there any additional modifications/configurations needed for that to work since I couldn't find any tags for ELK 6.6.1 in the dockerhub. Thanks in advance.

**Comment by gurkavcu** [comment]
I have been using wazuh 3.8.2 with elk 6.6.1. So far no problem. Compability matrix seems match also.
https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html

**Comment by 0x18katyan** [comment]
How did you build the image? I have modified the WAZUH_VERSION to 3.8.2-1 and FILEBEAT_VERSION to 6.6.1 in the DockerFile from wazuh-docker stable repo and build the image so far so good but I am being a bit doubtful about any other steps to follow other than that.

**Comment by manuasir** [comment]
Hello @0x18katyan and @gurkavcu .

We're about releasing a new image for `v6.6.1` and `v6.6.2` ELK support. Please stay tuned here.

Regards

**Comment by 0x18katyan** [comment]
Hey @manuasir, 
Is there any exact date for the release?

**Comment by manuasir** [comment]
Hello @0x18katyan ,

I cannot tell an exact date. We're currently working on the `v3.9.0`, it will be available in the upcoming weeks.

Regards

**Comment by 0x18katyan** [comment]
Hey @manuasir, sorry to bother you again, but can you list any major feature/s for the upcoming 3.9.0? Also, would 3.9.0 be compatible with ELK 6.6.1?

**Comment by manuasir** [comment]
Hi @0x18katyan ,

It's absolutely fine for me to help you with anything question that you may have. You can check the upcoming features in the [CHANGELOG](https://github.com/wazuh/wazuh/blob/3.9/CHANGELOG.md) of the `wazuh` repository, so the main functionality additions that you will find are the following:

- New module to perform **Security Configuration Assessment** scans. ([#2598](https://github.com/wazuh/wazuh/pull/2598))
- Collect network and port inventory for Windows XP/Server 2003. ([#2464](https://github.com/wazuh/wazuh/pull/2464))
- Included inventory fields as dynamic fields in events to use them in rules. ([#2441](https://github.com/wazuh/wazuh/pull/2441))
- Added an option _startup_healthcheck_ in FIM so that the the who-data health-check is optional. ([#2323](https://github.com/wazuh/wazuh/pull/2323))
- The real agent IP is reported by the agent and shown in alerts and the App interface. ([#2577](https://github.com/wazuh/wazuh/pull/2577))
- Added support for organizations in AWS wodle. ([#2627](https://github.com/wazuh/wazuh/pull/2627))
- Added support for hot added symbolic links in _Whodata_. ([#2466](https://github.com/wazuh/wazuh/pull/2466))
- Added `-t` option to `wazuh-clusterd` binary ([#2691](https://github.com/wazuh/wazuh/pull/2691)).
- Added options `same_field` and `not_same_field` in rules to correlate dynamic fields between events. ([#2689](https://github.com/wazuh/wazuh/pull/2689))
- Added optional daemons start by default. ([#2769](https://github.com/wazuh/wazuh/pull/2769))
- Make the Windows installer to choose the appropriate `ossec.conf` file based on the System version. ([#2773](https://github.com/wazuh/wazuh/pull/2773))

I hope that helps,

Cheers

**Comment by manuasir** [comment]
Hello @0x18katyan and @gurkavcu 

The images for `3.8.2_6.6.1` and `3.8.2_6.6.2` were already tagged and are also available in Dockerhub. Stay tuned for the upcoming support for the `6.7.0` version of ELK.
Thanks for you
