### ISSUE TITLE
docker compose fails on 4.8.0-beta3 due to wrong image version in docker-compose.yml in single-node ERROR: manifest unknown

### ISSUE THREAD

**Issue by TequilaNinjaHackerOne** [wazuh/wazuh-docker#1252]
https://github.com/wazuh/wazuh-docker/blob/401673e743ef521c347d754435ace0140aefb8b7/single-node/docker-compose.yml#L6

https://github.com/wazuh/wazuh-docker/blob/401673e743ef521c347d754435ace0140aefb8b7/single-node/docker-compose.yml#L49

https://github.com/wazuh/wazuh-docker/blob/401673e743ef521c347d754435ace0140aefb8b7/single-node/docker-compose.yml#L74

Those 3 locations I updated them from:
   image: wazuh/wazuh-manager:4.8.0
       image: wazuh/wazuh-indexer:4.8.0
    image: wazuh/wazuh-dashboard:4.8.0
and converted into:
   image: wazuh/wazuh-manager:4.8.0-beta3
       image: wazuh/wazuh-indexer:4.8.0-beta3
    image: wazuh/wazuh-dashboard:4.8.0-beta3

Please add to fix thanks you guys are so awesome for this project i <3 you.

Keep doing great work you are a much many motivation to much and many of people!

Full Error:
✘ wazuh.dashboard Error                                                                                                                                1.0s
 ✘ wazuh.manager Error                                                                                                                                  1.0s
 ✘ wazuh.indexer Error                                                                                                                                  1.0s
Error response from daemon: manifest for wazuh/wazuh-manager:4.8.0 not found: manifest unknown: manifest unknown

Changing 4.8.0 to 4.8.0-beta3 in docker compose yml fixes this issue :D

**Comment by rauldpm** [comment]
Hello @TequilaNinjaHackerOne 

Indeed, there is this difference between the tag and the DockerHub images, but this is done deliberately, after speaking with the team this is done to avoid adding unnecessary commits by adding and removing stage references, the idea is to use the tag and modify the file by adding the stage

Indeed, this may not be ideal, modifying a tag should not be the norm and that is why I am going to elevate this to improve the process of the issue https://github.com/wazuh/wazuh-docker/issues/1237, so that:

1. The 4.8.0 branch is modified to reference the new stage
2. Stage tag is created from branch 4.8.0
3. The 4.8.0 branch is restored removing the stage references, since now the branch could become a new testing stage or the production stage

Meanwhile, it is necessary to modify the docker-compose file with the corresponding stage. Sorry for the inconvenience and thank you for bringing this to our attention!

**Comment by TequilaNinjaHackerOne** [comment]
No worries you and the team have a great rest of your day/night thankyou so much for your time!
