### ISSUE TITLE
SSl certificates problem on the default docker-compose deployment

### ISSUE THREAD

**Issue by BAStos525** [wazuh/wazuh-docker#1295]
Hello!
When trying to deploy wazuh services in Docker within single-node, there are problems with SSL certificates: either `ERR_SSL_SSLV3_ALERT_CERTIFICATE_UNKNOWN` or `ERR_SSL_SSLV3_ALERT_BAD_CERTIFICATE` error from `wazuh.dashboard` container and on the different nodes. Wazuh web is accessible only from unsecured connection and not valid certificate.
All steps were executed from the official [guide](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment).
Certificated were generated by ` wazuh/wazuh-certs-generator:0.0.1` image from the guide.
Branch: master
Wazuh components version: v4.7.3

**Comment by davidcr01** [comment]
Hello.

This behavior is expected. In the Wazuh dashboard installation guide, self-signed SSL certificates generated during the Wazuh indexer installation were configured for the Wazuh dashboard. That's why I say this is expected.

You can use third-party certificates instead of self-signed ones in the Wazuh dashboard. I refer you to the following documentation: https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/configuring-third-party-certs/index.html

**Comment by BAStos525** [comment]
Thank you for reply. But I still have a fex questions to clarify.
1. Why the default SSL certificates created by `wazuh/wazuh-certs-generator:0.0.1` are producing `ERR_SSL_SSLV3_ALERT_BAD_CERTIFICATE` error in dashboard service logs and these certificates are not valid?
2. While issuing certificates by `certbot` tool, they are valid and connection is secure. But they are producing `ERR_SSL_SSLV3_ALERT_BAD_CERTIFICATE` error as well.
3. We can substitute `cerbot` tool or NGINX by other third-party tool for SSL, right? I'm talking about traefik, but there is just not a page about it.

**Comment by davidcr01** [comment]
Hello. In order to understand your problem, I need to ask you what documentation are you following to deploy the stack in Docker. In the first comment, you mention that you are deploying Wazuh `v4.7.3` but also that you are using the `master` branch, which has the `5.0.0` version in it.

Are you building the Docker images yourself with the `build-images.sh` script?
