### ISSUE TITLE
exec /entrypoint.sh: exec format error on RPI5 8gb and Bookworm

### ISSUE THREAD

**Issue by vnasser** [wazuh/wazuh-docker#1306]
has the problem in (https://github.com/wazuh/wazuh-docker/issues/924) been resolved?
I am using the Docker doc for installation: https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html
Thanks for the assist.
![wazuh2](https://github.com/wazuh/wazuh-docker/assets/41405614/968e81e0-993e-485b-8af0-7e373e70b27d)

**Comment by davidcr01** [comment]
Hello.

Yes, the reported problem was fixed. Wazuh added ARM support for the Wazuh manager and the Wazuh agent. You can check the packages list here: https://documentation.wazuh.com/current/installation-guide/packages-list.html

However, as we do not have ARM packages for the Wazuh indexer and Wazuh dashboard, we can not build ARM Docker images.

**Comment by davidcr01** [comment]
Hello. This issue is reported and worked in the following issue: https://github.com/wazuh/wazuh-packages/issues/1637

There is no news about this, but what I can tell you is that there is a branch with some changes in order to build the indexer and dashboard ARM packages here: https://github.com/wazuh/wazuh-packages/tree/1637-RPMSuportfoStack-to4.3

It would be necessary to apply these changes in the desired branch, depending on what version of Wazuh you want to deploy. I recommend you to fork the `wazuh-packages` repository, create a branch from the desired version and apply the changes to the mentioned branch.

I share you the steps to build the packages:

1. Go to your desired branch after applying the mentioned changes.
2. You must run the scripts on an arm64 host.
3. You must create the bases for both indexer and dashboard by executing the script as follows:
```
./generate_base.sh -a arm64 -s /tmp
```
This script is located at:
```
wazuh-packages/stack/dashboard/base
wazuh-packages/stack/indexer/base
```
The `-s` is to put the base file in `/tmp`, you can change the path or omit this parameter and an `output` directory will be created in the directory where the script is located.

4. You must create the packages by executing the following script:
```
./build_package.sh -a arm64 -s /tmp --base local --base-path /tmp
```
This script is located at:
```
wazuh-packages/stack/dashboard/rpm
wazuh-packages/stack/dashboard/deb
wazuh-packages/stack/indexer/rpm
wazuh-packages/stack/indexer/deb
```
the `-s` works the same as for step 3
`--base-path` has to contain the directory where you put the base in step 3

With this, you should be able to build your Wazuh indexer and Wazuh dashboard arm64 packages.

**Comment by vnasser** [comment]
@davidcr01 
Thank you so much. I will get on this.

**Comment by MorganKryze** [comment]
Hello @vnasser ,
Did you manage to get it working? If so, would you be able to share it?

**Comment by vnasser** [comment]
Nope. 4.9 server components will run on arm. You’ll need those hosted on x86. The rest of the pieces will work fine anywhere. On Jan 27, 2025, at 4:57 AM, Yann M. Vidamment ***@***.***> wrote:﻿
Hello @vnasser ,
Did you manage to get it working? If so, would you be able to share it?

**Comment by Xhoenix** [comment]
I was able to build the wazuh-indexer from [here](https://github.com/wazuh/wazuh-packages.git). I followed this official guide: https://documentation.wazuh.com/current/development/packaging/generate-indexer-package.html

You need to checkout the latest development branch.

**Comment by vnasser** [comment]
awesome. will check it out.
