### ISSUE TITLE
wazuh docker deployment issues

### ISSUE THREAD

**Issue by omar-timo08** [wazuh/wazuh-docker#1328]
Hello all! i have a probleme in my wazuh docker-compose.yml i started by the documentation wazuh https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html wazuh docker deployement single-node it works correctly but i want to mount the files in /data/wazuh and don't use /config and also i copied the /config files in /data/wazuh/config and the wazuh_indexer_ssl_certificate in my /data/wazuh/wazuh_indexer_ssl_certificate this my docker-compose looks like , but after docker-compose up the dasboard refuse connected to indexer , otherwise when i work with single-node in github it works what i can do ?
![a](https://github.com/wazuh/wazuh-docker/assets/110347943/4266e14f-0ba2-4914-92f5-325370912582)
![b](https://github.com/wazuh/wazuh-docker/assets/110347943/f016cadd-612b-487c-8b7c-5714cea3a4fc)
![c](https://github.com/wazuh/wazuh-docker/assets/110347943/f1cb18ab-9741-462d-a606-d05028f57092)
![d](https://github.com/wazuh/wazuh-docker/assets/110347943/ea7f202e-31a3-4055-b756-ba32f9e20f79)
![e](https://github.com/wazuh/wazuh-docker/assets/110347943/bdab4c2f-4b21-4070-a198-369e950af2f7)
![f](https://github.com/wazuh/wazuh-docker/assets/110347943/d70c56e1-6869-4316-8711-61cfd7710b80)

**Comment by vcerenu** [comment]
Hello @omar-timo08

I see that at the beginning of the cluster you have some orphan containers, I ask you if you can stop all the related containers before starting and clean the directories where they are saving the data.
Normally we use Docker volumes instead of bind mounts because they are more versatile for the tasks that containers perform, check if it is possible to use these, you can mount your fs on the directory in which Docker creates the volumes.
After that, start the cluster with `docker-compose up -d` and I ask you if you can send me the result of the `docker logs` command for the Wazuh indexer container that you are deploying.
