### ISSUE TITLE
Error deploying "driver failed programming external connectivity on endpoint"

### ISSUE THREAD

**Issue by rkuinkel** [wazuh/wazuh-docker#1335]
![Screenshot 2024-05-04 222020](https://github.com/wazuh/wazuh-docker/assets/14150326/b7dd1b0b-04cb-4710-a60a-6870a800e2a5)
![Screenshot 2024-05-04 222548](https://github.com/wazuh/wazuh-docker/assets/14150326/6d36a23d-5b56-42aa-8378-d2de8791e99f)
I am new to this.

**Comment by davidcr01** [comment]
Hello.

The problem is that, when deploying the single node Wazuh docker deployment, Docker can not expose the `55000` port of your machine because it is already being used by a Wazuh manager.
I wonder why you want a Wazuh manager and a single node Wazuh docker deployment in the same machine when the Docker deployment implies having a Wazuh manager inside the container.

If this is your desired environment, then you should redirect every Wazuh manager port of the Docker deployment by modifying the `docker-compose.yml` file:

https://github.com/wazuh/wazuh-docker/blob/ec76ea8d92c157357989746b4f1050c18bb379da/single-node/docker-compose.yml#L16-L20

If you just want a Docker deployment, please remove the Wazuh manager installed in your system and then, the port problem will be solved.
