### ISSUE TITLE
Enable additional Wazuh modules via Dashboard environment variables

### ISSUE THREAD

**Issue by BAStos525** [wazuh/wazuh-docker#1346]
In this [README section](https://github.com/wazuh/wazuh-docker?tab=readme-ov-file#environment-variables) it's written that Wazuh modules could be enabled/disabled via environment variables. By the way, when setting such vars `EXTENSIONS_AWS`, `EXTENSIONS_DOCKER`... to `=true` in docker-compose file, they are still not enabled in Dashboard. Only the default ones modules like `EXTENSIONS_AUDIT`, `EXTENSIONS_NIST` are on.

**Comment by CarlosALgit** [comment]
## Update Report
I deployed an environment with Docker trying to replicate the issues encountered. I'm currently checking the path of the issues to try to solve them.

**Comment by CarlosALgit** [comment]
## Update Report
I've had issues trying to replicate the problem to see the modules displayed on the new 4.8.0 Dashboard. I'm currently in the process of understanding how the Docker deployment works.

**Comment by CarlosALgit** [comment]
## Update Report
I've been learning how to check that an integration is working correctly on a Wazuh AIO installed with the assistant.

Then I deployed the Docker environment activating `- EXTENSIONS_VIRUSTOTAL=true` on the `docker-compose.yml` file for the dashboard. Then, I checked the environment variables on the Dashboard container and it was setted to true:

```
bash-5.2$ printenv | grep EXTENSIONS_VIRUSTOTAL
EXTENSIONS_VIRUSTOTAL=true
```

Then I went to the manager container to check the `ossec.conf` file but the integration for VirusTotal does not appear.

I tried to follow the code flow but I have found it impossible to understand when the change is being made to `ossec.conf` in order to add the integration module.

**Comment by teddytpc1** [comment]
@Enaraque, the modules are now enabled by default from version 4.8.0. So, we should remove all these variables.
