### ISSUE TITLE
Please tag releases on Docker Hub

### ISSUE THREAD

**Issue by ruffy91** [wazuh/wazuh-docker#143]
The latest 3.8.2_6.6.2 is not tagged, 3.8.2_6.6.1 is the newest tagged release but does not correspond to the latest tag.
Please fix this as it makes it easier to deploy the correct version of the containers.

**Comment by manuasir** [comment]
Hello @ruffy91 ,

It seems that Dockerhub is facing several issues since some weeks ago. We _cannot_  build new images from tags nor branches, and we're currently waiting for Dockerhub support, I'll let you know when  the problem's solved and our images can be built.
Sorry for the inconveniences,

Regards

**Comment by manuasir** [comment]
Hi, @ruffy91 

The `3.8.2_6.6.2` version was already tagged, you can also get the latest images from [Dockerhub](https://cloud.docker.com/u/wazuh/repository/list). Stay tuned here for the upcoming images for the latest `6.7.0` version of ELK.

This issue will be closed,don't hesitate to open a issue whenever you may need it.

Cheers
