### ISSUE TITLE
How to connect localhost agent with dockerized wazuh-server ?

### ISSUE THREAD

**Issue by sandipmgiri** [wazuh/wazuh-docker#150]
Hi All,

I have started wazuh-server (Wazuh, Elastic Stack and Nginx using docker-compose) on host X.X.X.117.

```
$ docker-compose up
$ docker-compose ps

          Name                        Command                               State                                                Ports
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
wazuhdocker_elasticsearch   elasticsearch                          Up         0.0.0.0:9200->9200/tcp, 9300/tcp
_1
wazuhdocker_kibana_1        /usr/local/bin/kibana-docker     Up        5601/tcp
wazuhdocker_logstash_1      /usr/local/bin/docker-entr        Up         0.0.0.0:5000->5000/tcp, 5044/tcp, 9600/tcp
                            ...
wazuhdocker_nginx_1         /bin/sh -c /entrypoint.sh            Up         0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
wazuhdocker_wazuh_1         /entrypoint.sh                          Up         0.0.0.0:1514->1514/udp, 0.0.0.0:1515->1515/tcp, 1516/tcp, 0.0.0.0:514->514/udp,
                                                                                                          0.0.0.0:55000->55000/tcp
```

Also , installed the wazuh-agent  on my localhost X..X.X.72. 

Now trying to connect the agent with dockerized server :
As suggested here https://documentation.wazuh.com/3.x/docker/container-usage.html, I have executed the command `/var/ossec/bin/agent-auth -m X.X.X.117` on agent host i.e. X.X.X.72. After that I got the below message :
```
2019/04/17 17:11:58 agent-auth: INFO: Started (pid: 6152).
2019/04/17 17:11:58 agent-auth: INFO: No authentication password provided.
2019/04/17 17:11:58 agent-auth: INFO: Connected to X.X.X.117:1515
2019/04/17 17:11:58 agent-auth: INFO: Using agent name as: XYZ-vm15
2019/04/17 17:11:58 agent-auth: INFO: Send request to manager. Waiting for reply.
2019/04/17 17:11:58 agent-auth: INFO: Received response with agent key
2019/04/17 17:11:58 agent-auth: INFO: Valid key created. Finished.
2019/04/17 17:11:58 agent-auth: INFO: Connection closed.

```
Here , I’m trying to understand : Is agent successfully connected to server ? or Do I need to execute more steps ? and When we can say that agent has been successfully connected ? Is there any way to send and receive data for connection confirmation?

Any inputs will be appreciated. Thanks in advance!

**Comment by manuasir** [comment]
Hi @sandipmgiri ,

After registering the agent using `agent-authd`, the service must be restarted:

```
systemctl restart wazuh-agent
```

In order to check the agent status, you can several ways to do it:

1. Check the `Agents` section of the app:

![image](https://user-images.githubusercontent.com/10210567/56287092-c6460680-611b-11e9-9787-68fd8b6ccaa7.png)

There you have a detailed list about your agents, including the status.

2. Request that information to the Wazuh API:

Using the `GET /agents` endpoint. For example, you can filter the request and extract only the status field:

![image](https://user-images.githubusercontent.com/10210567/56287228-102eec80-611c-11e9-8d47-8ed30f0bc99d.png)

3. Execute `/var/ossec/bin/agent_control -lc`, it returns which agents are currently connected to the manager.

You can get further information about checking the connection with the manager [here](https://documentation.wazuh.com/3.x/user-manual/agents/agent-connection.html).

Let me know if that helps.

Cheers

**Comment by sandipmgiri** [comment]
Thanks @manuasir for your quick response.
As you suggested , I have restarted the agent using command `systemctl restart wazuh-agent.`

Now I could able to see the connected agent :
```
$ docker exec -it wazuhdocker_wazuh_1  /var/ossec/bin/agent_control -l
Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh-manager (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: XYZ-vm15, IP: X.X.X.72, Active
```

Also I have checked , if an agent connected correctly by verifying if the UDP connection to the manager is established:
```
netstat -vatunp|grep ossec-agentd
udp   231040      0 X.X.X.72:41134       X.X.X.117:1514       ESTABLISHED 9152/ossec-agentd
```

After that, tried to check the agent status using Kibana’s IP address on port 5601 (default Kibana port). However I’m not able to see the Wazuh app in the below menu:

![image](https://user-images.githubusercontent.com/16284232/56354369-29ee3380-61f1-11e9-83a6-da811bd6bc6a.png)


Looks like I'm missing something here. Please provide your inputs on this.Thanks!

**Comment by manuasir** [comment]
Hi @sandipmgiri ,

Sorry for the late response.
I wasn't able to reproduce this. It seems that the deployment process of our kibana container was wrong, were you already able to resolve it? If not, please indicate here some details about the process:

- which version are you currently using?
- are you using docker-compose?

Also, please tell me the steps you followed in order to reproduce it.

Cheers

**Comment by manuasir** [comment]
Hello @sandipmgiri ,

I just wanted to follow up on this. Were you able to resolve your problem?

Regards

**Comment by manuasir** [comment]
This issue is going to be closed due to inactivity. Don't hesitate to open a new one if you need it.

Regards
