### ISSUE TITLE
Complete documentation: Describe each environment variable

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#160]
Hello folks,

I think it'd be great if every `ENV VAR` used in the images would  be explained in the `README.md`, and also it can be included in the `Wazuh official documentation` once they're ready.
 
Feel free to share your thoughts on this here.

Regards

**Comment by webguywalker** [comment]
this would be awesome, I spent today searching the docs and reading the env2yaml.go file to figure out which env vars may or may not work :-/

**Comment by manuasir** [comment]
Hello @webguywalker ,

We're working on it, please stay tuned here.

**Comment by tnyeanderson** [comment]
This really needs addressing. I have been playing a game of hide-and-go-seek with my configuration options for the last few days. Was finally able to find the API_USER and API_PASS by looking through the docker files, but I still have *so* many questions and I'm about to give up because there is just so little information about very critical configuration options for the docker images.

I'm happy to pitch in where I can, but I don't know much about most of the systems that use these environment variables. I've created a PR #283 with a template to quickly add short explanations and usage examples to the README. I have filled in the few that I am able. If knowledgeable members of the team have a few spare minutes (which are always hard to come by), using them to type up an explanation for just a few of these variables could help get someone up and running with a lot less frustration.

Many thanks to the Wazuh team for the hard work!!

**Comment by manuasir** [comment]
This is awesome @tnyeanderson, for sure we will use your contribution to complete the env vars documentation. The main reason we have this issue currently stalled is because of the full rework of our Docker images, probably several env vars will be removed and new ones can be added. You can keep the track of this rework here https://github.com/wazuh/wazuh-docker/projects/6.

I'm adding this task to the project as part of the rework. Thank you again @tnyeanderson for the contribution and all you guys for the patience.

Cheers

**Comment by tnyeanderson** [comment]
I'm happy to help where I can, and thank you for the link to the rework. I will be following along. By chance are the following variables (or similar) being added to the kibana container during the rework?

```
API_USER
API_PASS
USAGE_DATA_OPT_OUT
```

Or am I missing some other configuration option? I always have to re-enter my API credentials and answer "NO" to usage analytics every time I go down. Unsure if this is expected behavior.

The last variable could be set to `true` to opt out of elasticsearch/kibana usage analytics (blue banner at the top of the kibana dashboard page, not sure if this belongs in the kibana container or the elasticsearch one...)

Again, thank you for your work on this project!

**Comment by xr09** [comment]
@tnyeanderson since 3.11 our Kibana container accepts those variables 

https://github.com/wazuh/wazuh-docker/blob/380ba92708c46becc92f3606bdc655373be8b1f7/kibana/config/wazuh_app_config.sh#L4-L7

Will keep in mind the `USAGE_DATA_OPT_OUT` for the rework, granted that's a bit annoying.

**Comment by tnyeanderson** [comment]
@xr09 THANK YOU! Don't know how I missed those options.

Thanks for keeping the USAGE_DATA_OPT_OUT in mind!!

**Comment by xr09** [comment]
@tnyeanderson good news, looks like since Kibana `7.5.0` it is possible to disable telemetry by using the environment variable `TELEMETRY_ENABLED=false`.

Here is the change on elastic repo: https://github.com/elastic/dockerfiles/blame/7.5/kibana/bin/kibana-docker#L187

Our latest release is using kibana `7.5.1` container so you can start using this variable already.

**Comment by tnyeanderson** [comment]
@xr09 you just made my day! Thank you very much for the tips :)
