### ISSUE TITLE
Clustering of wazuh-indexer using Docker is not possible

### ISSUE THREAD

**Issue by lcndsmr** [wazuh/wazuh-docker#1600]
Hi everyone, 

I noticed that the dockerfile for the wazuh-indexer is not exposing 9300, making it impossible to create an opensearch cluster using docker. 

I would like to have the possibility to cluster my opensearch. Is there any reason for this?

Thank you for your time!

**Comment by vcerenu** [comment]
Hello

Port 9300 is not exposed to the outside because the idea of ​​Docker deployment is that all nodes are within the same net, in this case, all nodes are deployed within the same Docker network and in the case of Kubernetes they are within the same cluster network.

If you need to expose that port, you can fork our repository, modify the `build-docker-images/build-images.yml` file within the repository and then create your own images. In our documentation we have a section where we explain how to build them:
https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#build-docker-images-locally

**Comment by lcndsmr** [comment]
Thanks for clarification!
