### ISSUE TITLE
[error] 28#28: *4 no live upstreams while connecting to upstream

### ISSUE THREAD

**Issue by AwwalQuan** [wazuh/wazuh-docker#1620]
I got the following error message during the multi-node Docker deployment while testing [Release 4.10.0 - Alpha 3 - E2E UX tests - Deployment on Docker](https://github.com/wazuh/wazuh/issues/26784).

```
multi-node-nginx-1            | 2024/11/12 14:04:18 [error] 28#28: *4 no live upstreams while connecting to upstream, client: 192.168.132.132, server: 0.0.0.0:1514, upstream: "mycluster", bytes from/to client:0/0, bytes from/to upstream:0/0
```
See full log output: [cluster_deployment.txt](https://github.com/user-attachments/files/17717808/cluster_deployment.txt)

The deployment was successful. However, we need to investigate the error message further.

Thanks.

**Comment by YisDav** [comment]
# Description

In order to reproduce the error, and to detect possible root cause and functionality implications, a latest version Ubuntu server was provisioned on an AWS EC2 machine, on which the multi-node `wazuh-docker` deployment was run.

However, despite running the deployment for version `4.10.0-alpha3`, the nginx error could not be replicated. When starting the container orchestrator and running the services, the error is not displayed. Thus, evidence of the multi-node deployment is included, as well as tests on the connectivity of the managers `master` and `worker` nodes to each other and to the `indexer` node.

## Master node

![image](https://github.com/user-attachments/assets/1f912a8f-b36b-4bb1-883f-c1dfc716a07f)

## Worker node

![image](https://github.com/user-attachments/assets/b58bc23d-195b-4ad2-a865-9d18210e1b50)

## Full log output

[results.log](https://github.com/user-attachments/files/17817269/results.log)

**Comment by teddytpc1** [comment]
We were not able to reproduce the error.

**Comment by teddytpc1** [comment]
The message is expected as the `nginx` container is starting before the `wazuh-master/worker` ones:
- Nginx log:
`2024/11/27 09:25:52 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.31.69.239, server: 0.0.0.0:1514, upstream: "172.18.0.3:1514", bytes from/to client:0/0, bytes from/to upstream:0/0`
- Wazuh-master first log:
`2024-11-27T09:26:30.717Z        INFO    [publisher_pipeline_output]     pipeline/output.go:145  Attempting to reconnect to backoff(elasticsearch(https://wazuh1.indexer:9200)) with 3 reconnect attempt(s)`
- Wazuh-worker first log:
`2024-11-27T09:26:09.777Z        INFO    memlog/store.go:124     Finished loading transaction log file for '/var/lib/filebeat/registry/filebeat'. Active transaction id=40`
