### ISSUE TITLE
Mount volumes instead of creating symbolic links

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-docker#183]
Hi team,

Right now, we create symbolic links for the folders that we want to store in the volume (`/var/ossec/data`). Example:
- `/var/ossec/etc` -> `/var/ossec/data/etc`.

This can cause several issues. For example, if Wazuh overwrites a file using `move`, we will lose the symbolic link. This is happening for `/var/ossec/queue/agents-timestamp`.

We should remove the symbolic links, instead, mount paths. Example:
- Volume: `/mnt/wazuh`
- `/mnt/wazuh/ossec/etc` is mounted in `/var/ossec/etc`.
- `/mnt/wazuh/ossec/queue` is mounted in `/var/ossec/queue`.
- `/mnt/wazuh/ossec/...` is mounted in `/var/ossec/...`.
- `/mnt/wazuh/filebeat/etc` is mounted in `/etc/filebeat`.
- `/mnt/wazuh/filebeat/var/lib` is mounted in `/var/lib/filebeat`.
- `/mnt/wazuh/postfix/etc` is mounted in `/etc/postfix`.

**Comment by manuasir** [comment]
Hi team,

Today I've been trying to mount the full `/var/osse/etc` folder into a volume located in my host with no luck. The behavior that I noticed is the following:
- Wazuh manager is installed correctly in the container, no installation error was received.
- Then the container was stopped and a volume was attached by `docker-compose`:
```
volumes:
  - './data/wash:/var/ossec/etc'
```
- When the container is recreated again, the volume is attached and then the `/var/ossec/etc` folder gets empty, maybe because of this:
   - The volume is empty when created, so Docker empties the container located folder.
   - From that point, the communication between container and host is bidirectional, and any added file is also reachable from both host and container.

I've also tried `bind mounts` with the same result, so I'll keep this ticket updated so you can track any news. Of course, any ideas would be appreciated.

Regards

**Comment by manuasir** [comment]
Related and detailed issue https://github.com/wazuh/wazuh-docker/issues/214, this can be closed.
