### ISSUE TITLE
Problem with rancher 2.2.4 and wazuh stack 3.9.2_6.8.0

### ISSUE THREAD

**Issue by Cobra1978** [wazuh/wazuh-docker#211]
Hi.

I've deployed the Wazuh stack (wazuh, logstash, elasticsearch, kibana) from Dockerhub Wazuh images on a Rancher 2.2.4 cluster, kubernetes version is 1.13.5-rancher1-3

The problem is that the kibana-wazuh app dosen't work, the only thing i see in the log of the wauh plugin is
"wazuh-api:check Daemons","message":"socket hang up"

No errors in wazuh logs or elasticsearch logs.

IOther parts are working well: Wazuh recievs notifications and with kibana i can explore the logstash indices without any issue.

My old installation on Rancher 1.6.28 with Kubernetes 1.12.7-rancher1-1-1 the Stack is working well, i can use the Kibana-Wazuh plugin.

Someone can help me to understand and resolve the problem?

Thanks and best regards.

**Comment by jm404** [comment]
Hi @Cobra1978,

Sorry for the late response, 

We are checking this and will write back with results as soon as possible.

Best Regards,

Jose

**Comment by jm404** [comment]
Hi @Cobra1978,

We found an issue related to Manager and API versioning when installing them in the container, this would cause to install the latest instead of the desired version of each branch/tag.

We applied the changes and the new images are created. Please reinstall it and verify the Manager and API is correct and they are the same.

If the problem persists please let me know.

Thanks for your report, it's really appreciated

Best regards

Jose

**Comment by Cobra1978** [comment]
Hi, and sorry for the late response.

I can confirm that the issue is closed, thanks and best regards
