### ISSUE TITLE
Change circuit breakers of Wazuh image

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#214]
Hello team,

Since several issues were reported (https://github.com/wazuh/wazuh-docker/issues/183, https://github.com/wazuh/wazuh-docker/issues/177, https://github.com/wazuh/wazuh-docker/issues/149), it was decided to completely refactor the Wazuh Docker image. This should involve structural changes such:

### Changes

- [x] No longer symbolic links.
- [x] No duplicated environment variables
- [x] Minor improvements.

### Tests

- [x] Configuration files .yml are properly loaded

- [x] Owner and permissions are maintained ~( Fails with RIDS permissions )~

- [x] Agents are not lost after migration

- [x] No symbolic links in the 3.10 volume

- [x] Wazuh API configuration is restored

- [x] Wazuh API works as expected

- [x] Wazuh Cluster works without problems

- [x] Logs are restored 

- [x] Client.keys is restored

- [x] Agent groups are preserved

Further tests were performed, check https://github.com/wazuh/wazuh-docker/issues/214#issuecomment-533998623 for the list of changes

This issue may be updated when new requirements are decided to be implemented.

Regards

**Comment by manuasir** [comment]
Working on this branch [3.10-wazuh-refactor](https://github.com/wazuh/wazuh-docker/tree/3.10-wazuh-refactor).

**Comment by manuasir** [comment]
Since this has been successfully tested, the next step is to include a migration script for handling volumes that were created in previous versions for persistence purposes. As this rework includes a breaking change in how volumes are used, it'd be necessary to adapt to the new structure.

The script should pass the following tests after being run:
- [ ] Migration of old volumes with created configurations.
- [ ]

**Comment by jm404** [comment]
Hi team,

### Migration approach

In new release (3.10), the folders stated in the current release (3.9) are already mounted. 

For example in 3.9 we backed up `/var/ossec/queue/db`, and in 3.10  whole `/var/ossec/queue` is mounted. 

Following this approach, when restoring our configuration from 3.9 volume into the new container, this config will be automatically synced in the new volume. This is what the migration scripts tries to achieve. 

Some permissions and owners problems may appear in the restoration process, I'm working to diagnose and fix them.

### Migration script changes
I did some changes to the code to allow copying folders using `key:value` specifications.

An example of declaring folders:

https://github.com/wazuh/wazuh-docker/blob/5f9b4241e87d1f31c2d6bd9cb45edd2b0f01f3cc/wazuh/migration/02-volume_loader.sh#L15-L20

This way source and destination can be specified with low efforts for users that want to backup different folders.

The whole script is located at: [02-volume_loader.sh](https://github.com/wazuh/wazuh-docker/blob/3.10-wazuh-refactor/wazuh/migration/02-volume_loader.sh)

You can check the changes at: [3.10-wazuh-refactor](https://github.com/wazuh/wazuh-docker/commits/3.10-wazuh-refactor)

Best regards,

Jose

**Comment by jm404** [comment]
Hi team,

The previously mentioned migration approach was tested on migrations from `3.9.5` to `3.10.0`.

The process did successfully back up the configuration from the previous version to a named volume. In order to ensure that most complex configurations are properly saved we configured and tested the following settings were properly restored:

- [ ] Custom `ossec.conf`

- [ ] Agents

- [ ] Groups

- [ ] Groups configuration

- [ ] Cluster configuration

- [ ] Alerts

- [ ] Logs

Use cases:

- [ ] Audit

- [ ] FIM

- [ ] Netcat

- [ ] Openscap

- [ ] Vulnerability detector


All the previous configurations were successfully restored and agents were preserved.

We are working on branches [dev-3.9.5-migration](https://github.com/wazuh/wazuh-docker/tree/dev-3.9.5-migration) and [dev-3.10.0-wazuh-migration](https://github.com/wazuh/wazuh-docker/tree/dev-3.10-wazuh-migration)

Best regards

Jose
