### ISSUE TITLE
Enable GeoIP on release wazuh/wazuh:3.9.5_7.2.1

### ISSUE THREAD

**Issue by anyon486** [wazuh/wazuh-docker#233]
Hello,

I try to enable the geolocation feature because it is not enabled as default.
This is not documented so I tried to:
- enable the _geoip_ pipeline in the **filebeat** configuration
- add the following pipeline to Kibana
`PUT _ingest/pipeline/geoip
{
  "description": "Add geoip info",
  "processors": [
    {
      "geoip": {
        "field": "client.ip",
        "target_field": "client.geo",
        "ignore_missing": true
      }
    },
    {
      "geoip": {
        "field": "source.ip",
        "target_field": "source.geo",
        "ignore_missing": true
      }
    },
    {
      "geoip": {
        "field": "destination.ip",
        "target_field": "destination.geo",
        "ignore_missing": true
      }
    },
    {
      "geoip": {
        "field": "server.ip",
        "target_field": "server.geo",
        "ignore_missing": true
      }
    },
    {
      "geoip": {
        "field": "host.ip",
        "target_field": "host.geo",
        "ignore_missing": true
      }
    },
    {
      "geoip": {
        "field": "@src_ip",
        "target_field": "host.geo",
        "ignore_missing": true
      }
    },
    {
      "geoip": {
        "field": "src_ip",
        "target_field": "host.geo",
        "ignore_missing": true
      }
    }
  ]
}`

I noticed that the package _libgeoip-dev_ is not installed in the wazuh-docker images, so I suppose the provided docker image was not built in order to provide geo location feature.

Could you please provide more details, if you have, how I can enable this feature?
Thanks a lot in advance.

**Comment by jm404** [comment]
Hi @anyon486,

We recently updated the Filebeat template of our docker tag `v3.9.5_7.2.1` please do a git pull to get the latest changes.

With the new version, the geoIP is integrated and no changes are required. There is a pipeline that will match the following fields of the alert:
- `data.srcip`
- `data.win.eventdata.ipAddress`
- `data.aws.sourceIPAddress`

The first one is included by default in most Linux systems, the second one is related to Window systems and the third one is related to the AWS integration.

Keep in mind that geoIP requires the IP to be public in order to be able to locate it, for example the IP: 10.2.1.2 (subnet) won't trigger geoIP but the 216.23.2.15 (public) will do.

Hope this resolves your doubt, let me know if you need further help

Best regards

Jose

**Comment by anyon486** [comment]
Hi @jm404 ,
It works! Thank you.
Best regards,
Michele

**Comment by jm404** [comment]
Hi @anyon486,

Glad to hear it worked for you, don't hesitate to ask us anytime!

Best regards

Jose
