### ISSUE TITLE
Wazuh 3.10.0 / On Manager Reboot, Agent's Registration Date goes back to 1970/01/01

### ISSUE THREAD

**Issue by narayaar** [wazuh/wazuh-docker#253]
|Wazuh version|Component|Install type|Install method|Platform|
| 3.10.0 | Wazuh Manager | Agent | Packages | CentOS 7.6 |

Hello Team: I have the Wazuh Manager running as a container, via your published image.

When the agent is installed the first time around, the registration date shows the local time the agent was added, and this information is reflected correctly via the Kibana DB via the browser's local TZ.  All is well.

However, when the Wazuh Manager container is stopped/started, the agent's registration date goes back to 1970/01/01 00:00:00, with the Kibana DB correctly reflecting that as well, along with the browser's local TZ.

$ curl -s --header 'Authorization: Basic XXXXXXXXXXXXXXXXXXXXX' -XGET -k https://XXXXXXXXXXXXXXXXXXXx:55000/agents/015 | jq . | egrep 'dateAdd|lastKeep'
"lastKeepAlive": "2019-09-30 04:50:13",
"dateAdd": "1970-01-01 00:00:00"

Please do let me know how this can be remediated.  I currently have 200 agents that show 1970 as the year of registration.

Thanks,
Arun

**Comment by jm404** [comment]
Hi @narayaar,

After reviewing your problem, I tried to replicate it with success.

The error you state appears when the `/var/ossec/queue/agents-timestamp` file is removed between manager restarts. I removed mine and restarted the manager and obtained:

**Comment by jm404** [comment]
After debugging the related issues in our [Slack Community Channel](https://wazuh.com/community/join-us-on-slack/) we find out the following:

In my try, the `agents-timestamp` was properly backed up and restored but when @narayaar  restarted the containers the `agents-timestamp` appeared empty so it is not getting backed up properly.

The symbolic link doesn't seem to work properly in some situations. In order to find a workaround of this, @narayaar mounted the `agents-timestamp` file in a volume so this way it's loaded before the Wazuh Manager starts up. After this, the Agents Registration and Last keep alive dates are properly restored.

Further investigation is required in order to check why the `agents-timestamp` is not getting backed up properly. Things point to a problem with symbolic links, checking this could give useful info about the problem.

Best regards

Jose
