### ISSUE TITLE
Can't disable ML (XPACK_ML) in Elasticsearch container

### ISSUE THREAD

**Issue by batidiane** [wazuh/wazuh-docker#269]
My host doesn't support SSE4.2 instructions used by ES ML.

```
wazuh_es         | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.3.2.jar:7.3.2]",
wazuh_es         | "Caused by: org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].",
wazuh_es         | "at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:497) ~[?:?]",
```

Tried to deactivate ML by setting the environment variable XPACK_ML to false in docker-compose.yml but it doesn't work. I tried to modify the parameter directly in the elasticsearch Dockerfile and rebuild the container but it doesn't help. I have no custom elasticsearch.yml file, use the default one generated when the container is being created.
After analyzing the ES container build process, I noticed that when the ES config file (elasticsearch.yml) doesn't exist, it is first created in entrypoint.sh to configure xpack ML feature. Later, in config_cluster.sh the cluster configuration is added to the ES config file. However, instead of appending the new configuration parameters, it overrides the existing parameters because of the use of the redirection operator **'>'** instead of **'>>'**:

config_cluster.sh line 25:
```
cat > $elastic_config_file << EOF
# cluster node
network.host: 0.0.0.0
node.name: $CLUSTER_MASTER_NODE_NAME
node.master: $CLUSTER_NODE_MASTER
cluster.initial_master_nodes: 
  - $CLUSTER_MASTER_NODE_NAME
# end cluster config"
```
config_cluster.sh and line 40:
```
cat > $elastic_config_file << EOF
# cluster node
network.host: 0.0.0.0
node.name: $CLUSTER_NODE_NAME
node.master: false
discovery.seed_hosts: 
  - $CLUSTER_MASTER_NODE_NAME
  - $CLUSTER_NODE_NAME
# end cluster config" 
```

**Comment by jm404** [comment]
Hi @batidiane,

The blocks at `config_cluster.sh` are part of an if-else conditional statement:

https://github.com/wazuh/wazuh-docker/blob/2c31757953156d9fc3e1a0573c929e0bef1dc99a/elasticsearch/config/config_cluster.sh#L22-L55

Only one of them will be activated depending on `$CLUSTER_NODE_MASTER` value. In order to add a setting (`xpack.ml.enabled: false` in your case), you can edit the  `config_cluster.sh` configuration file to add your settings:

```
if [[ $CLUSTER_NODE_MASTER == "true" ]]; then
# Add the master configuration
# cluster.initial_master_nodes for bootstrap the cluster
cat > $elastic_config_file << EOF
# cluster node
network.host: 0.0.0.0
node.name: $CLUSTER_MASTER_NODE_NAME
node.master: $CLUSTER_NODE_MASTER
cluster.initial_master_nodes: 
  - $CLUSTER_MASTER_NODE_NAME
xpack.ml.enabled: false    # new custom setting
# end cluster config" 
EOF

elif [[ $CLUSTER_NODE_NAME != "" ]];then
# Remove the old configuration
remove_single_node_conf $elastic_config_file
remove_cluster_config $elastic_config_file

cat > $elastic_config_file << EOF
# cluster node
network.host: 0.0.0.0
node.name: $CLUSTER_NODE_NAME
node.master: false
discovery.seed_hosts: 
  - $CLUSTER_MASTER_NODE_NAME
  - $CLUSTER_NODE_NAME
xpack.ml.enabled: false    # new custom setting
# end cluster config" 
EOF
fi
```
--

Replace `image: wazuh/wazuh-elasticsearch:3.10.2_7.3.2` with `build: elasticsearch` in the [docker-compose.yml](https://github.com/wazuh/wazuh-docker/blob/master/docker-compose.yml) to tell Docker to build the image locally. Also, remember to execute `docker-compose up --build` to force the local build with your new changes.

After that, you will see the changes in your ES Docker container:

![image](https://user-images.githubusercontent.com/46649922/68106906-62cacd00-fee3-11e9-8e1f-35f6edaa137c.png)


Hope it helps to answer your question,

Best regards

Jose

**Comment by manuasir** [comment]
Hello @batidiane ,

Was that useful for you? Please, let me know if we can close this issue.
Thanks.

**Comment by batidiane** [comment]
Hello,
Thanks for the explanations. I used a slightly different method to correct the issue. I modified config_cluster.sh but just by changing:
`cat > $elastic_config_file << EOF`
into
`cat >> $elastic_config_file << EOF`

By this, I am not overriding the config file already created in entrypoint.sh which is executed before config_cluster.sh. Also, this method allowed me to use the parameter XPACK_ML to enable/disable my container ML capability.

The issue can be closed.
