### ISSUE TITLE
Image wazuh:3.9.0_6.7.1 wazuh-api empty reply

### ISSUE THREAD

**Issue by Hongbin-Cai** [wazuh/wazuh-docker#276]
Hi team! I am deploying Wazuh on Google Kubernete Engine and found that the Wazuh-master's image seems having some errors related to Wazuh's configuration. 

I have tried two versions:
- wazuh/wazuh:3.9.0_6.7.2
- wazuh/wazuh:3.9.0_6.7.1

Error
![image](https://user-images.githubusercontent.com/57362120/69439797-a9a72800-0d15-11ea-91ce-4ed79c803346.png)

Here are the major errors from /var/ossec/logs/ossec.log.:
- wazuh-modulesd:vulnerability-detector: ERROR: (5404): The package name could not be obtained.
- wazuh-modulesd:vulnerability-detector: ERROR: (5493): The version of '(null)' could not be extracted.
- wazuh-modulesd:vulnerability-detector: ERROR: (5405): SQL error: NOT NULL constraint failed: VULNERABILITIES.OS
- wazuh-modulesd:vulnerability-detector: ERROR: (5409): Could not refresh the REDHAT DB.
- wazuh-modulesd:vulnerability-detector: ERROR: (5426): CVE database could not be updated.
- wazuh-modulesd:osquery: WARNING: Results file '/var/log/osquery/osqueryd.results.log' not available: No such file or directory (2). Retrying in 60 sec.

I ssh to the pod running Wazuh-manager and the API is not responding if I curl port 55000 or 1515. But their services are running.
The commands I used to test API are

> curl [host]:55000 -u foo:bar

and

> curl [host]:55000

Inside the container I used localhost, and outsider I used the clusterIP given by GCP.

![image](https://user-images.githubusercontent.com/57362120/69452862-bbe28f80-0d30-11ea-9698-ff6a09f4856d.png)

Also, log from /var/ossec/logs/api.logs. Based on the log, there might be some errors but I cannot identify what exactly the problem from the text showing to me.
![image](https://user-images.githubusercontent.com/57362120/69458657-e129ca80-0d3d-11ea-8ecf-5c2a8d09d991.png)

**Comment by jm404** [comment]
Hi @Hongbin-Cai,

## Vulnerability detector errors

The vulnerability-detector module shows different errors as stated in the logs you provided.

I tried to reproduce them in my local environment without success.

To have detailed info about this, please start the `vulnerability-detector` module with debug flags:

1.- **Kill the current `wazuh-modulesd` daemon with:**

``` pkill -f wazuh-modulesd ```

2.- **Start the daemon in debug mode:**

``` /var/ossec/bin/wazuh-modulesd -dd ```

Please note this will start the module in verbose mode and you will find a lot of log entries in your `/var/ossec/logs/ossec.log`.

3.- **Filter logs**

```cat /var/ossec/logs/ossec.log | grep wazuh-modulesd:vulnerability-detector ``` 

Also, try with different filters like `vulnerability` to check for another entry that could reveal valuable information.

This thread shows similar logs which may be related to yours: https://groups.google.com/forum/#!topic/wazuh/IAm5djXOJH8


## Osquery error logs

Logs:

```
wazuh-modulesd:osquery: WARNING: Results file '/var/log/osquery/osqueryd.results.log' not available: No such file or directory (2). Retrying in 60 sec.
```

The `osquery` module is disabled by default, that log shows that the stated file is not detected, if you desire to use `osquery` it you have to install the `osquery` package and enable it. You can check a detailed guide at: 

https://documentation.wazuh.com/3.10/user-manual/capabilities/osquery.html

Otherwise, if you don't want to use that moudle you can disable it at `/var/ossec/etc/ossec.conf` by setting `<disabled>yes</disabled>` under the `<wodle name=vulnerability-detector>`.


## API not working

The Wazuh API has credentials sets by default `foo:bar`, you can call the api with:

```
curl -u foo:bar -k -X GET "https://127.0.0.1:55000/manager/info?pretty"
```

Which should respond something like:

```
{
   "error": 0,
   "data": {
      "path": "/var/ossec",
      "version": "v3.9.0",
      "compilation_date": "Thu May  9 15:20:15 UTC 2019",
      "type": "manager",
      "max_agents": "14000",
      "openssl_support": "yes",
      "ruleset_version": "3914",
      "tz_offset": "+0000",
      "tz_name": "UTC"
   }
}
```

Regarding your error logs:

![image](https://user-images.githubusercontent.com/46649922/69526194-f125f200-0f69-11ea-8123-38f51479c021.png)

The red logs show unauthenticated errors related to the curl calls you did.

The blue logs show an error when trying to fetch information from the manager, probably from Kibana.

Please check the Kibana container and verify if the service is running. You can also check `/usr/share/kibana/optimize/wazuh-logs/wazuhapp.log` for logs related with the Wazuh Kibana plugin

Also, verify you properly configured the Wazuh API Credentials in your Kibana:


![image](https://user-images.githubusercontent.com/46649922/69526399-60034b00-0f6a-11ea-9cb7-bddff2a497c0.png)


I suspect the Blue errors are also related to credentials as in my container they are shown like this

```
WazuhAPI 2019-11-25 08:58:24 foo: [::ffff:172.19.0.5] GET /manager/status? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:24 foo: [::ffff:172.19.0.5] GET /version? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:24 foo: [::ffff:172.19.0.5] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:24 foo: [::ffff:172.19.0.5] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:25 foo: [::ffff:172.19.0.5] GET /agents/summary? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:29 foo: [::ffff:172.19.0.5] GET /manager/status? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:29 foo: [::ffff:172.19.0.5] GET /version? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:29 foo: [::ffff:172.19.0.5] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:29 foo: [::ffff:172.19.0.5] GET /agents/000? - 200 - error: '0'.
WazuhAPI 2019-11-25 08:58:29 foo: [::ffff:172.19.0.5] GET /version? - 200 - error: '0'.
WazuhAPI 2019-11-25 09:00:01 foo: [::ffff:172.19.0.5] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '0'.
WazuhAPI 2019-11-25 09:00:01 foo: [::ffff:172.19.0.5] GET /cluster/status? - 200 - error: '0'.
```

Notice the `foo` prefix which doesn't appear in your logs.


Hope it helps to debug your errors, let me know with the results

Best regards

Jose

**Comment by Hongbin-Cai** [comment]
Hi Jose,

Your command reveal the real problem! 

 `curl -u foo:bar -k -X GET "https://127.0.0.1:55000/manager/info?pretty"`

The API no reply problem is because I request API using http but the API uses https. 

Actually the log contained the `foo` but I didnt screenshot that part when posting the issue, sorry for that!
![image](https://user-images.githubusercontent.com/57362120/69568773-4245de00-0f8a-11ea-8b21-5d4ce370a2bc.png)

This is the result message from the given command.
```
root@wazuh-manager-master-0:/# curl -u foo:bar -k -X GET "https://127.0.0.1:55000/manager/info?pretty"
{
   "error": 0,
   "data": {
      "path": "/var/ossec",
      "version": "v3.9.0",
      "compilation_date": "Fri May  3 17:44:23 UTC 2019",
      "type": "manager",
      "max_agents": "14000",
      "openssl_support": "yes",
      "ruleset_version": "3914",
      "tz_offset": "+0000",
      "tz_name": "UTC"
   }
}

```

But for the blue part, the problem haven't solved. I will comment here later when having enough info of it.

Thank you for your help!

**Comment by Hongbin-Cai** [comment]
Hi Jose,

Today I am working on making Kibana connection to Wazuh API. I met an unclear issue that the api returns the following error when manually visit https://[wazuh-host]:55000/agents or when setup Wazuh setting in Kibana.
 
![image](https://user-images.githubusercontent.com/57362120/69670189-54df1680-1061-11ea-91ae-31fb3d1c3f0e.png)

This issue cannot be solved if restart wazuh-api service in the container but it is solved after I re-deploy Wazuh-manager.

Now I can connect to Wazuh using the same setting.
![image](https://user-images.githubusercontent.com/57362120/69670125-2d884980-1061-11ea-9fd6-25a5b7731e06.png)

**Comment by jm404** [comment]
Hi @Hongbin-Cai 

I see you marked the post as "(Solved)" so I assume you managed to fix it by restarting the Wazuh-Manager.

Let me point out that the API checks if required daemons related to Wazuh are running. If one of them fails, the API will show errors with: "There is a failed process" message in them.

You can check [Wazuh Daemons](https://documentation.wazuh.com/3.10/user-manual/reference/daemons/index.html) for detailed information about them.

I'm closing the issue if you have any other questions or errors feel free to reopen it anytime!

Best regards

Jose

**Comment by Hongbin-Cai** [comment]
Hi Jose,

I want to re-open this issue but I cannot so I comment here. There is another issue I

**Comment by jm404** [comment]
Hi @Hongbin-Cai,

As the log states, some of the Wazuh Manager daemons are failing. In order to properly debug it let me ask you for some logs which will help us to find the error:

- The content of `cat /var/ossec/logs/ossec.log | grep -E "WARN|ERROR"`
- The output of `ps -aux | grep -E "ossec|wazuh"` in the Master  when the API is failing

Thanks in advance.

Best regards,

Jose

**Comment by Hongbin-Cai** [comment]
Hi Jose,

Log from Kibana
![image](https://user-images.githubusercontent.com/57362120/69823798-f6887400-11d7-11ea-9a3e-52bb5d7fac3c.png)

output from `ps -aux | grep -E "ossec|wazuh`. 
```
root@wazuh-manager-master-0:/# ps -aux | grep -E "ossec|wazuh"
root          39  0.0  0.0   4240   744 ?        Ss   Nov27   0:00 runsv wazuh
root          40  0.0  0.0   4240   692 ?        Ss   Nov27   0:00 runsv wazuh-api
ossec         56  0.0  0.4 954876 72032 ?        Sl   Nov27   0:23 /usr/bin/nodejs /var/ossec/api/app.js
root          57  0.0  0.0   7612   276 ?        S    Nov27   0:00 tail -f /var/ossec/data/logs/api.log
root         196  0.0  0.0 120996  5812 ?        Sl   Nov27   0:07 /var/ossec/bin/ossec-authd
ossec        204  0.0  0.0 645240  4676 ?        Sl   Nov27   0:49 /var/ossec/bin/wazuh-db
root         225  0.0  0.0  38924  2816 ?        Sl   Nov27   0:03 /var/ossec/bin/ossec-execd
ossec        238  0.0  0.1 913092 17096 ?        Sl   Nov27   0:50 /var/ossec/bin/ossec-analysisd
root         246  0.0  0.0 113844  5372 ?        Sl   Nov27   0:29 /var/ossec/bin/ossec-syscheckd
ossecr       262  0.2  0.0 449760  3920 ?        Sl   Nov27   2:45 /var/ossec/bin/ossec-remoted
root         271  0.0  0.0 407580  3620 ?        Sl   Nov27   0:48 /var/ossec/bin/ossec-logcollector
ossec        297  0.0  0.0  38920  4160 ?        Sl   Nov27   0:07 /var/ossec/bin/ossec-monitord
ossec        376  0.0  0.2 127616 33696 ?        S    Nov27   0:52 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root         398  0.0  0.0   7612   352 ?        S    Nov27   0:00 tail -f /var/ossec/data/logs/ossec.log
root      381635  0.0  0.0  14516   984 pts/0    S+   17:19   0:00 grep --color=auto -E ossec|wazuh
```

output from service
`root@wazuh-manager-master-0:/# service wazuh-api status`
WAZUH-API is running.

root@wazuh-manager-master-0:/# service wazuh-manager status
```
wazuh-clusterd is running...
wazuh-modulesd: Process 306 not used by Wazuh, removing...
wazuh-modulesd not running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
```

**Comment by Hongbin-Cai** [comment]
And indeed it is the daemon failing.  `service wazuh-manager restart` can make Kibana call Wazuh normally again.

**Comment by jm404** [comment]
Hi @Hongbin-Cai

Looking at your daemons, it looks like the `wazuh-modulesd` is failing for some reason.

In order to debug it, please edit the `/var/ossec/etc/internal_options.conf` and set the option `wazuh_modules.debug=0` to `wazuh_modules.debug=2`, this will start the daemon in verbose mode.

Please note this will flood your `/var/ossec/logs/ossec.log` but will help us to find what is causing the error.

After modifying the configuration, restart the Wazuh Manager and search the logs for errors with: 

- `cat /var/ossec/logs/ossec.log | grep -E "ERROR|CRITICAL|WARN"`
- `cat /var/ossec/logs/ossec.log | grep "wazuh-modulesd"`

This way you should see some information related to your case.

Also, feel free to paste the logs here (make sure to obfuscate any sensitive info) so we can review them and have a better diagnostic.

Best regards,

Jose

**Comment by Hongbin-Cai** [comment]
Hi Jose.

The log file is too large to put here and because it is flooding that makes harder to check the log info. I put the previous log here, it contains some verbose info and I replaced it with an empty file in the server.  And I checked, there is no sensitive info inside. 

[ossec.log](https://drive.google.com/file/d/1LfRfvIvle_RTgOQmIrZt6tA73gwFdGRG/view?usp=sharing)

**Comment by jm404** [comment]
Hi @Hongbin-Cai,

I requested access to the file, please review it and let me know if you accept my request

Best regards,

Jose

**Comment by Hongbin-Cai** [comment]
Hi Jose,

I changed the link permission. The default permission makes it sharable only from people in a group. Sorry for that !

**Comment by Hongbin-Cai** [comment]
Sorry Jose,

I forget to set `wazuh_modules.debug=2`. But Wazuh was running in verbose mode. Here is the log files, hope this work.

`cat /var/ossec/logs/ossec.log`: [log](https://drive.google.com/file/d/1nBr80kgnfKhFJ9hSRx6vymGr1Xk24U_9/view?usp=sharing)

`cat /var/ossec/logs/ossec.log | grep -E "ERROR|CRITICAL|WARN"`: [log](https://drive.google.com/file/d/18MjZ-2dX3Rx9iJemNLE5t15Mx5prZVwj/view?usp=sharing)

**Comment by Hongbin-Cai** [comment]
Now I changed the setting and use this command to start the daemon. I am not sure if they are conflicted with each other. Maybe one's log level is lower....etc.

the command : `/var/ossec/bin/wazuh-modulesd -dd`

> root@wazuh-manager-master-0:/# vim /var/ossec/etc/internal_options.conf
root@wazuh-manager-master-0:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd: Process 398220 not used by Wazuh, removing...
wazuh-modulesd not running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
root@wazuh-manager-master-0:/# /var/ossec/bin/wazuh-modulesd -dd
2019/11/29 18:40:02 wazuh-modulesd[839456] wmodules-osquery-monitor.c:78 at wm_osquery_monitor_read(): DEBUG: Logpath read: /var/log/osquery/osqueryd.results.log
2019/11/29 18:40:02 wazuh-modulesd[839456] wmodules-osquery-monitor.c:84 at wm_osquery_monitor_read(): DEBUG: configPath Readed: /etc/osquery/osquery.conf
2019/11/29 18:40:02 wazuh-modulesd[839456] wmodules-vuln-detector.c:140 at set_oval_version(): WARNING: The specific definition of the Red Hat feeds is deprecated. Use only redhat instead.
root@wazuh-manager-master-0:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
root@wazuh-manager-master-0:/# 

the setting:

![image](https://user-images.githubusercontent.com/57362120/69885890-81876e00-12ad-11ea-94e0-7489e7e116e8.png)

**Comment by jm404** [comment]
Hi @Hongbin-Cai,

I reviewed your logs and the module failing is `vulnerability-detector`:
```
ERROR: (5409): Could not refresh the REDHAT DB.
ERROR: (5426): CVE database could not be updated.
2019/11/29 16:08:22 wazuh-modulesd:vulnerability-detector[398218] wm_vuln_detector.c:843 at wm_vuldet_sql_error(): ERROR: (5405): SQL error: NOT NULL constraint failed: VULNERABILITIES.OS
```

It seems like the `vulnerability-detector` module is not being able to update the Redhat database. We are investigating this in order to find out which is causing the error. 

I assume you have a Redhat agent connected, could you provide the output of `/etc/os-release`? Also, sharing any other information you consider important about the Agent like packages or AMI version will help a lot to debug the error.

You can reestablish the `vulnerability-detector` in order to try to fix the error. Remove the content of `/var/ossec/queue/vulnerabilities/` and restart the Wazuh Manager, this will force `vulnerability-detector` to recreate the database.

Let me link a probably related issue: https://github.com/wazuh/wazuh/issues/4135

We are really sorry for the inconvenience, will update you as soon as we have conclusions on this.

Best regards,

Jose

**Comment by Hongbin-Cai** [comment]
Hi, Jose

This is the the output of `cat /etc/os-release`

> BUILD_ID=11647.293.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=ed61fe8747ee554d56511964d50289d4bf547083
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=73
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=73
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos

**Comment by Hongbin-Cai** [comment]
And the wazuh_modulesd stopped after forced DB re-establishment. Here is the log:

`cat /var/ossec/logs/ossec.log`: [log](https://drive.google.com/file/d/1viz9KpPhsQ0PqYzvz7M1zG0D0QHAO6HX/view?usp=sharing)

`cat /var/ossec/logs/ossec.log | grep -E "ERROR|CRITICAL|WARN"`: [log](https://drive.google.com/file/d/1JsHSGIgbVf0yKEGJB6gGCbRwyEtrHKFE/view?usp=sharing)

`cat /var/ossec/logs/ossec.log | grep "wazuh-modulesd"`: [log](https://drive.google.com/file/d/15NJ5CmQxLuCyfpNXrzci4AaHll9avUcz/view?usp=sharing)

**Comment by Hongbin-Cai** [comment]
I think now the problem becomes that Wazuh-manager says vulnerability scan finished but no record I can find in alerts.json/alerts.log

**Comment by Hongbin-Cai** [comment]
After checking `ossec.conf`, I think Wazuh is only using CVE feed, thats not an issue. And the wazuh-modulesd periodical stopping problem doesnt happen for 5 days. So I close this issue.
