### ISSUE TITLE
local_rules.xml

### ISSUE THREAD

**Issue by RANGERBEE** [wazuh/wazuh-docker#31]
Hello,

  Could you tell me best way to use my own local_rules.xml file in addition to the wazuh rules and parsers?

I tried to mount an external volume with the docker-compose file , with failure each time I try to start all with "docker-compose up"..

Thank you!

**Comment by RANGERBEE** [comment]
Trying to wrap my head around the logic..

Could it be the run.sh script for the wazuh container as well as the Dockerfile for the wazuh container that both contain references to- 
DATA_PATH=/var/ossec/data
VOLUME ["/var/ossec/data"]

The line in the docker-compose file is commented out for wazuh image-
#    volumes:
#      - my-path:/var/ossec/data
#      - my-path:/etc/postfix

I have exported the /var/ossec/data/etc and /var/ossec/ruleset directories from the container and would like to add my local_rules.xml file in and set the volume mapping correctly.

Could you help with telling me what should be configured in the run.sh script, the Dockerfile, where I should place my local_rules.xml?

I planned on setting the wazuh/wazuh docker-compose file to map the drive to prepared folders-
volumes:
 - ./wazuh/config/ossec/data/ruleset:/var/ossec/data/ruleset

Please let me know if there is a problem with this logic.



Thank you.

**Comment by mjflve** [comment]
Hi,

The wazuh container will map several config files/folders to `/var/ossec/data` at the first run inside the container, this is intended because the Wazuh Manager runs into a chrooted environment, so in order export all config files from the container to the host please try the following:

1. Stop and remove current container: `docker-compose down`
2. Create the destination folder on the host: `mkdir -p /var/ossec`
3. Uncomment the volume section on the wazuh container: `/var/ossec:/var/ossec/data`
4. Start the containers again: `docker-compose up -d`

After some time you should be able to see config related files on the host

```
# ls  /var/ossec/
api  etc  logs  process_list  queue  ruleset  stats  var
```

Then, you can configure your `local_rules.xml` by modifying the `/var/ossec/etc/rules/local_rules.xml` file on the host.

I hope it helps,

Regards,
