### ISSUE TITLE
Filebeat module installed at entrypoint

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-docker#374]
Hello team,

Currently, the Wazuh filebeat module has to be downloaded and installed at the entrypoint: https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/01-config_filebeat.sh

This has an inconvenience, the Wazuh docker image can't be used in environments without internet connection.

Is there any reason to not do it at the Dockerfile?

Best regards,
Miguel

**Comment by xr09** [comment]
Duly noted @migruiz4, this step should be done on the build step and not on the entrypoint. This is fixed on the upcoming release (4.0) but I'm thinking we should provide a solution for current 3.x users, since it's not a breaking change at all.

I'll bring this up to the team and we'll give some thought. Thanks for reporting!

**Comment by xr09** [comment]
https://github.com/wazuh/wazuh-docker/pull/378 will fix this, filebeat is now installed on build stage.
