### ISSUE TITLE
problem installing the wazhu docker :( elasticsearch:9200; Connection refused

### ISSUE THREAD

**Issue by mitraed** [wazuh/wazuh-docker#43]
hi m getting these errors, and i dont think elastic cache created ok with the docker . (ubuntu 16.4)

kibana_1         | Elastic is unavailable - sleeping
logstash_1       | [2018-03-24T21:46:19,121][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://elasticsearch:9200/, :path=>"/"}
logstash_1       | [2018-03-24T21:46:19,125][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
kibana_1         |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
kibana_1         |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to elasticsearch:9200; Connection refused

from the outside i can reach 9200 but from the inside not really.

root@net-wazhu:~# netstat -anp | egrep -i 9200
tcp6       0      0 :::9200                 :::*                    LISTEN      4274/docker-proxy

my iptables are : 
root@net-wazhu:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.25.0.3           tcp dpt:55000
ACCEPT     tcp  --  anywhere             172.25.0.3           tcp dpt:1515
ACCEPT     udp  --  anywhere             172.25.0.3           udp dpt:1514
ACCEPT     udp  --  anywhere             172.25.0.3           udp dpt:syslog
ACCEPT     tcp  --  anywhere             172.25.0.5           tcp dpt:5000
ACCEPT     tcp  --  anywhere             172.25.0.6           tcp dpt:https
ACCEPT     tcp  --  anywhere             172.25.0.6           tcp dpt:http
ACCEPT     tcp  --  anywhere             172.25.0.2           tcp dpt:9200

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

but the docker itself throwing me out 
root@net-wazhu:~# docker exec -i -t 668f1be1b64e /bin/bash
[root@elasticsearch elasticsearch]# netstat -anp | egrep -i 9200
bash: netstat: command not found
[root@elasticsearch elasticsearch]# 
root@net-wazhu:~#

**Comment by mjflve** [comment]
Hi @mitraed,

The elasticsearch container needs a special sysctl configuration, can you please take a look at [here](https://documentation.wazuh.com/current/docker/wazuh-container.html#requirements).

On any case, please send us the following output from the docker host machine:

- `docker-compose ps`
- `docker-compose logs  elasticsearch`
- `curl localhost:9200`

Thanks in advance!

Best Regards,

**Comment by hansaliyad1** [comment]
I am still having this problem. Trying to figure this out since last three days. I follow exact instructions given [https://documentation.wazuh.com/current/docker/wazuh-container.html#requirements](here). 

Here is my output of 

- `docker-compose ps`
`        Name                      Command              State                                                    Ports                                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
ossec_elasticsearch_1   /entrypoint.sh elasticsearch   Up      0.0.0.0:9200->9200/tcp, 9300/tcp                                                                        
ossec_kibana_1          /bin/sh -c /entrypoint.sh      Up      5601/tcp                                                                                                
ossec_logstash_1        /bin/sh -c /entrypoint.sh      Up      0.0.0.0:5000->5000/tcp, 5044/tcp, 9600/tcp                                                              
ossec_nginx_1           /bin/sh -c /entrypoint.sh      Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp                                                                
ossec_wazuh_1           /entrypoint.sh                 Up      0.0.0.0:1514->1514/udp, 0.0.0.0:1515->1515/tcp, 1516/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:55000->55000/tcp`

- `curl localhost:9200`
Curl is not responding.

Let me know if you need logs. I will really appreciate if you can assist me.

Thank you!

**Comment by srikarduplo** [comment]
You need to increase the max_map_count on your host. Refer to https://documentation.wazuh.com/3.11/docker/wazuh-container.html
