### ISSUE TITLE
Easily find wazuh size data in ELK

### ISSUE THREAD

**Issue by pandamasta** [wazuh/wazuh-docker#525]
Hi,

According to the documentation https://documentation.wazuh.com/current/installation-guide/requirements.html#all-in-one-deployment. There is a ratio of 37 between Storage in Wazuh Manager and Storage in Elasticsearch

I would like to compare the size of data in ELK (as admin) and in alerts.log in my wazuh-manager.

Could you please explain how to visualize this amount of data in ELK as:

- request/s ; 
- data volume / day / agent

This data can be efficiently used to size an infrastructure. 

Cheers

**Comment by alberpilot** [comment]
Hello @pandamasta 

  Sorry for the late response. In order to get the Elasticsearch data size, indeed, you can use the Elasticsearch API endpoint `_stats`:
  
![image](https://user-images.githubusercontent.com/3830293/140484963-c169baa1-f75a-4b45-87c4-d91dc3e4a6a0.png)

The value `size_in_bytes` will give you the total information (it must be under `_all` value in order to have all cluster node size). 

Another more rudimentary method could be to go to the host folder `/usr/lib/elasticsearch` and get a `du -sh *`. You should do it in all nodes and manually get the sum. 
For Wazuh manager logs you need to use this method, go to `/var/ossec/logs/alerts` and run `du -sh *`. 

Hope it help.

Regards, 
Alberto R

**Comment by alberpilot** [comment]
I proceed to close this issue. Please don't hesitate to re-open the issue again if needed. 

Regards, 
Alberto R

**Comment by pandamasta** [comment]
Many thanks for all your feedback @alberpilot 
All that I needed ;)
Cheers
