### ISSUE TITLE
Need image wazuh-manager only !

### ISSUE THREAD

**Issue by kendyblack** [wazuh/wazuh-docker#547]
I need an image with wazuh-manager 4.15 and filebeat 7.10.2. Help me !

**Comment by vcerenu** [comment]
Hi @kendyblack 

We have images uploaded to Docker Hub for the version you are looking for

Wazuh Manager + Filebeat repository for ElasticSearch.
https://hub.docker.com/r/wazuh/wazuh

Wazuh Manager + Filebeat repository for OpenDistro
https://hub.docker.com/r/wazuh/wazuh-odfe

If you check the compatibility matrix, version **4.1.5** is compatible with the version of Filebeat you are requesting, also if you see in the tag **v4.1.5** of this repository you can check the **Dockerfile** file in the **wazuh-odfe** directory with the one where the **_wazuh/wazuh_** and **_wazuh/wazuh-odfe_** images were created, in order to check that they are using the corresponding version

**Comment by kendyblack** [comment]
i want images just have wazuh-manager end filebeat.It will have no configuration related to Elasticsearch. It will have no configuration related to Elasticsearch. I can then configure the Elasticsearch connection
