### ISSUE TITLE
Flood of o.e.d.c.m.IndexNameExpressionResolver in log 

### ISSUE THREAD

**Issue by pandamasta** [wazuh/wazuh-docker#558]
Hi,

In log there is a flood of warning

`elasticsearch_1    | [2021-11-30T10:45:10,645][DEPRECATION][o.e.d.c.m.IndexNameExpressionResolver] [elasticsearch] this request accesses system indices: [.kibana_1], but in a future major version, direct access to system indices will be prevented by default
`
Cheers

**Comment by vcerenu** [comment]
Hello @pandamasta 

This flood of errors is an opendistro bug, which prolongs those errors several times.

Checking inside the repository they have an issue about it in which they are working:
https://github.com/opensearch-project/OpenSearch/issues/1108

Within it they give the idea of disabling that level of log as workaround, but it does not seem like a good solution because it can hide other important things.

If you don't have a large number of messages, I recommend to ignore it. I did a test and did not get too many messages. 

Regards
