### ISSUE TITLE
wazuh password change

### ISSUE THREAD

**Issue by AceCoronnet9034** [wazuh/wazuh-docker#578]
I used docker-compose to deploy wazuh, and now the password is admin / admin. How can I change the login password? docker-compose.yml Change login or admin in YML file

**Comment by vcerenu** [comment]
Hello @AceCoronnet9034 
`docker-compose.yml` creates a test stack, it only uses the `odfe `defaults configurations and does not persist data.
If you want to modify installation parameters, I recommend that you use the stack that is created with the `production-cluster.yml` script. In this script, the` internal_users.yml` file is mounted as a volume, which has all the users that are created with the hash of their password. You can change the hash of the `admin `user in that file and that will create the user with a password that you define.
To correctly deploy the stack, check the documentation, where we explain step by step how to deploy and what certificates you have to create, or you can present your own certificates:
https://documentation.wazuh.com/current/docker/wazuh-container.html#production-deployment
In case it is just a test, you can mount the internal_users.yml file inside the odfe container so that it takes the passwords you want to assign to it as it is mounted in the `production-cluster.yml` file:
```
- ./production_cluster/wazuh-indexer/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml
 ```
You must change the passwords inside the` docker-compose.yml` to the new password, start the stack with docker-compose and once the services are up you enter the Opendistro container:
```
docker exec -it wazuh-docker_elasticsearch_1 bash
```
In there you have to run the `securityadmin` script:
```
cd /usr/share/elasticsearch/plugins/opendistro_security/tools/
sh securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert /usr/share/elasticsearch/config/root-ca.pem -cert /usr/share/elasticsearch/config/kirk.pem -key /usr/ share/elasticsearch/config/kirk-key.pem
```
Once you finish changing the password, you must change the password with which Filebeat connects, which is configured on the first start:
```
docker exec -it wazuh-docker_wazuh_1 bash
vi /etc/filebeat/filebeat.yml
```
Inside the file you modify the password and then restart the container.


Let me know if any of the alternatives worked for you.

**Comment by alberpilot** [comment]
Hello @AceCoronnet9034 

I proceed to close this issue. Please don't hesitate to open again if you need further assistance.

Regards
Alberto R
