### ISSUE TITLE
wazuh-docker 4.3.0 improvements (second iteration)

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#599]
The following improvements were asked for 4.3.0:
- [x] `docker-compose.yml` has the service `wazuh1.indexer` that must be replaced by `wazuh.indexer`
- [x] Wazuh manager volume names start by `ossec_`, i.e: `ossec_etc`, `ossec_logs`, etc. It must start with `wazuh_` instead of `ossec_`. 
- [x] Review the documentation, section:
```
SELinux

On distributions with SELinux enabled out-of-the-box, it is necessary to either re-context the files or put SELinux into Permissive mode for docker-elk to start properly. For example, on Red Hat and CentOS the following command will apply the proper context:

$ chcon -R system_u:object_r:admin_home_t:s0 docker-elk/
--


```
why `docker-elk`?
- [x] Remove HTTPS redirection from Nginx and use directly Wazuh dashboard. 
- [x] Investigate if Docker has a native balancing method in order to replace Nginx load balancing. 
- [x] Design a new repository distribution, with a folder called `single-node` for the simple docker deployment and a `multi-node` folder for the production deployment. A common folder, at the same level, has to be done and use for common assets. Two new README must be added for those folders.

**Comment by vcerenu** [comment]
The name of the wazuh.indexer service was modified, which required modifying several configuration files. Tests were carried out to verify the correct execution of the test and production environments.

Volume names will be changed from `ossec_` to `wazuh_`.

We are working on the creation of the `single-node` and `multi-node` directories and the movement of the necessary configuration files for each one, in addition to the creation of a separate directory for the build of the Docker images.

Regarding Load Balancer in Docker, it does not bring this feature within its base
https://docs.docker.com/engine/reference/commandline/network_create/

To be able to generate a Load Balancer it is necessary to activate Swarm, but this option is rarely used since Swarm requires additional configurations in Docker and they preferably choose Kubernetes
https://docs.docker.com/engine/swarm/
