### ISSUE TITLE
The indexer/dashboard certs folder should have 500 permissions and certificates 400 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#602]
The permissions given to `certs` folder (the certificates containing folder) should change to 500, which is more restrictive. Certificates should have 400.

**Comment by fcaffieri** [comment]
### Update report

Fixing permissions issues, as manager, indexer and dashboard permissions are mounted to the same volume, and then root-ca is shared by all 3 components. By placing the permissions in 400 with a different id (1000 come from the indexer and dashboard and 999 from the manager) the manager does not see the certificate.
It is required to generate a new certificate for manager, a copy of the current one, according to the config.yml tag server. In order to then mount it to another volume as root-ca.
I am implementing a config.yml parser, since for the multi-node installation, there are more than 1 server, therefore it translates to more than one certificate to copy (worker and master).
