### ISSUE TITLE
use version 4.3 and kibana can't use port 443

### ISSUE THREAD

**Issue by Hello-Linux** [wazuh/wazuh-docker#628]
kibana can't run on port 443 and the error is  FATAL  Error: listen EACCES: permission denied 0.0.0.0:443

**Comment by miyoyo** [comment]
The unprivileged user running Kibana appears to not have sufficient capabilities to bind to that port, is there a reason why wazuh.dashboard is accessible directly, instead of using NGINX, like the previous config?

**Comment by fcaffieri** [comment]
Hello @Hello-Linux,

Could you tell us what type of installation you have done? single-node or multi-node?

Could you tell us what branch/tag did you use to deploy?

Could you share with us the certs.yml that you have used? or the config file /usr/share/wazuh-dashboard/opensearch_dashboards.yml
Avoid sharing sensitive information

What system and distribution did you install on?

It seems to be a permission problem with your installation, but the docker installation places the necessary permissions. So could you share with us inside the dashboard container what permissions the following file has?
 /usr/share/wazuh-dashboard/node/bin/node

Any other information that you consider pertinent to your environment or to the installation that you have made regarding permissions, could be of help to understand where the problem comes from.

I am waiting for the information.
Thank you.

**Comment by miyoyo** [comment]
So, it looks like it works on a fresh install:

<details>
Using Ubuntu Server 22.04 LTS
 - downloaded from https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso
 - SHA256: 84aeaf7823c8c61baa0ae862d0a06b03409394800000b3235854a6b38eb4856f
 - SHA1: d5ea5b7bac040ea1eb9fd74fa0b5eecde7bb0bff

Installed on VMware Workstation 16 Pro (16.1.2 build-17966106)
On a VM with:
 - 2 Cores
 - 4GB of RAM
 - 32GB of Storage
 (Otherwise, default configuration)

Machine Install:
 - English
 - Keyboard: Belgian / Belgian
 - Edition: Full version of Ubuntu Server
 - Network config: DHCP
 - Disk as LVM, ubuntu-lv extended from 15GB to 30GB
 - Profile
   - Name: test_user
   - Server name: test_server
   - Username: test_user
   - Password: test_user
 - Did NOT install OpenSSH
 - Featured server snaps: Docker
 - Waited until all updates were applied then rebooted.

Container install:
- `sysctl -w vm.max_map_count=262144`
- `docker ps -a` to create the docker folder in the snap folder
- `cd snap/docker`
- `sudo su`
-  following exactly as https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#multi-node-deployment says
  - `git clone https://github.com/wazuh/wazuh-docker.git -b 4.3 --depth=1`
  - `cd wazuh-docker/multi-node`
  - `docker-compose -f generate-indexer-certs.yml run --rm generator`
  - `docker-compose up -d``
- `docker-compose logs --follow wazuh.dashboard`

And this works correctly.
</details>

I feel like the issue might happen either because of the migration of older containers, or because of an older kernel, I had the issue on CentOS 7, I don't have the machine anymore, so I'll try a fresh install of CentOS 7 and report back.

**Comment by miyoyo** [comment]
It indeed breaks on CentOS 7!

<details>
Using CentOS 7 2009 Minimal, downloaded from http://centos.cu.be/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso

- SHA256: 07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
- SHA1: 9d452fe09a71394df437fd82e3fb263f02878f98

Same machine as above

Machine Install:
- English
- Keyboard: Dutch; Flemish (Belgian)
- Timezone: GMT+1
- Mountpoints: Automatic
- Network: DHCP
- Root Password: test_user

Container install:

- `yum upgrade`
- `restart`
- `yum install -y yum-utils git`
- `yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo`
- `yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin`
- `systemctl start docker`
- `cd /opt`
- `sysctl -w vm.max_map_count=262144`
- `git clone https://github.com/wazuh/wazuh-docker.git -b 4.3 --depth=1`
- `cd wazuh-docker/multi-node`
- `docker-compose -f generate-indexer-certs.yml run --rm generator`
- `docker-compose up -d`
- `docker-compose logs --follow wazuh.dashboard`
</details>

And the error happens:
![image](https://user-images.githubusercontent.com/3525610/167700444-fd2cc91c-ab32-4392-b0e1-9d9353c9415e.png)

**Comment by fcaffieri** [comment]
We generate the following issue to deal with this problem. https://github.com/wazuh/wazuh-docker/issues/636

**Comment by alberpilot** [comment]
Solved here: https://github.com/wazuh/wazuh-docker/pull/637
