### ISSUE TITLE
Permissions for persistants volumes in mounted volume

### ISSUE THREAD

**Issue by rpoulard** [wazuh/wazuh-docker#679]
Hello team,

Is it possible to add a way to verify, the deployment of production-cluster for persistant volume OUT of the VM ?

Case : Using docker with a NFS mounted volume ( in /mnt/..  via fstab )

- Changed volumes of docker-compose.yml  

When deployed, this is the errors i could have :  

1. Docker Compose not available to create data folders if not existant

- If already existant -> issue with permissions

2. Files in /config got the wrong permissions per default ( after git clone of wazuh repo with root )

- Also have the error with user ( not root )

Is there a way to automatically check and launch a script for permissions verifications and adaptations
There is also no documentation for exported data ( like NFS mount point )

Thanks
Regards,

**Comment by vcerenu** [comment]
Hello @rpoulard 

Sorry for the delay in response.

As of version 4.3, when starting the Wazuh manager container, a verification of the owner users of the application files is performed. In case of having permission problems, make a correction so that the permissions do not generate problems at the start of the application.

On mounting volumes, you can previously declare them within the compose so that it takes them as the volumes that are created automatically:

```
volumes:
   indexer-data:
     drivers:local
     driver_opts:
       or: bind
       type: none
       device: /mnt/indexer-data
```
