### ISSUE TITLE
Docker image wazuh-manager does not have requests library for integrations

### ISSUE THREAD

**Issue by x4team** [wazuh/wazuh-docker#738]
I used single-node and docker-compose configuration, and wanted to enable integration for slack/or custom, but it didn't work, since the wazuh/wazuh-manager image:4.5.0 does not have python3-pip installed by default and the requests library. Why was this excluded from the image? After all, in this case, integration does not work. Thanks!

**Comment by rauldpm** [comment]
Hello @x4team, version `4.5.0` (`master` branch currently) is a version still under development for which there are no final packages available. The current production version is `4.3.9`

Regarding the `python3-pip` package, it is true that it is not installed by default in the image because we seek to provide the lightest images possible, and said package is not an essential requirement for the operation of the Wazuh server, but rather it is necessary for integrations, which are optional to use.

As a note, the Wazuh server includes an embedded python with a `3.9.9` version, these binaries can be found in the `/var/ossec/framework/python/bin` path.

```
root@wazuh:/# /var/ossec/framework/python/bin/pip3 --version
pip 21.2.4 from /var/ossec/framework/python/lib/python3.9/site-packages/pip (python 3.9)
root@wazuh:/# /var/ossec/framework/python/bin/python3 --version
Python 3.9.9
```

I understand that you have obtained an error, could you provide us with said error and how to reproduce it?

**Comment by rauldpm** [comment]
Hello @x4team 

I agree with you that it would be interesting to add said package to the image and I have already communicated it to the team to discuss this, in any case, the Slack integration should work without the need to install the `python3-pip` or `python3-requests` packages due to the embedded python itself of Wazuh that I have commented before, this also applies for the upgrade of the Wazuh server.

As I commented in my previous message, I would need to know what error you get or what unwanted behavior you get to be able to help you better, please make sure that the Slack webhook is correct and that you do not have any errors in the ossec log file: `/var/ossec/logs/ossec.log`

Slack integration: https://documentation.wazuh.com/current/proof-of-concept-guide/poc-integrate-slack.html

**Comment by Viator99** [comment]
H!I, 
Hope to find all you well! 😁

Sorry for the intromission, i had the same mistake.
I resolved it with a python script.
I noticed that it is happening too with responsive-active.

Could this issue be correlated to that?

**Comment by rauldpm** [comment]
Hello @Viator99 

Which version are you using? Do you mean Active response?

It would be necessary to know what specific error or behavior you get. Could you share the configuration that is giving you problems?

Please, run the following command on the Wazuh server node and show us the output obtained:

- cat /var/ossec/logs/ossec.log | grep -i -E "error|critical|fatal|warning"

Regards, Raúl.

**Comment by alberpilot** [comment]
I proceed to close this issue due to inactivity. Please don't hesitate to re-open if necessary.
