### ISSUE TITLE
local_rules.xml

### ISSUE THREAD

**Issue by bla-ckbox** [wazuh/wazuh-docker#749]
Hi,

I allow myself to ask again a question that had already been raised in the past, and for which the answer is no longer suitable, given the changes made in version 4.3...

What is the best way to make permanent a custom rules file local_rules.xml hosted on the Docker host ?

Past issue: https://github.com/wazuh/wazuh-docker/issues/31

**Comment by rauldpm** [comment]
Hello @bla-ckbox and thanks for your patience.

I would not recommend making a permanent change to this file as it may be subject to changes in the future if you wish to modify it, instead, I suggest using a volume where you have the changes you want to apply, this can be done as follows:

1. Create the `local_rules.xml` file on the host (in this example it will be `custom/local_rules.xml`)
2. Edit the `docker-compose.yml` file and add the following line in the Wazuh service manager, in the volumes section, where `./custom/local_rules.xml` should be a relative or absolute path to your rules file.

```
- ./custom/local_rules.xml:/wazuh-config-mount/etc/rules/local_rules.xml
```

3. Save the edit and start the Wazuh stack

```
docker-compose up
```

During docker-compose execution, you should see a message like this:

```
wazuh.manager_1    | Identified Wazuh configuration files to mount...
wazuh.manager_1    | '/wazuh-config-mount/etc/ossec.conf' -> '/var/ossec/etc/ossec.conf'
wazuh.manager_1    | '/wazuh-config-mount/etc/rules/local_rules.xml' -> '/var/ossec/etc/rules/local_rules.xml'
wazuh.manager_1    | [cont-init.d] 0-wazuh-init: exited 0.
```

Once initialization is complete, if you go into the Wazuh manager container and do a `cat` to the file in question, you should see its contents.

---

If you still want to make a permanent change to that file, you should build the Wazuh manager image by adding what is necessary so that during the build, the Dockerfile includes that file, but keep in mind that this solution may not always be the best, since If at any time you need to modify it, you would have to redo the image, or if you use volume, you would lose said changes in favor of the content of the volume. 

For this, you would have to do the following:

1. Add to the Wazuh manager Dockerfile before the `permanent_data.env` references (https://github.com/wazuh/wazuh-docker/blob/v4.3.10/build-docker-images/wazuh-manager/Dockerfile) the following lines:

```
COPY --chown=wazuh:wazuh custom/local_rules.xml /var/ossec/etc/rules/local_rules.xml
RUN chmod 660 /var/ossec/etc/rules/local_rules.xml
```

2. From the root of the cloned repository, create the images, to do this run:

```
bash build-docker-images/build-images.sh
```

3. Start the Wazuh stack

```
docker-compose up
``` 

Regards, Raúl.

**Comment by alberpilot** [comment]
Closed due to inactivity. Please don't hesitate to open it again if necessary.

**Comment by timrekelj** [comment]
I followed the process that @rauldpm suggested (added `local_rules.xml` to `docker-compose.yml`), the only difference is that I added `local_decoder.xml` too:
```
volumes:
  - ${PWD}/config/local_decoder.xml:/var/ossec/etc/local_decoder.xml
  - ${PWD}/config/local_rules.xml:/var/ossec/etc/local_rules.xml
```

When I try to run docker-compose up, I get this error:
```
wazuh_1          | Traceback (most recent call last):
wazuh_1          |   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.7-py3.9.egg/wazuh/core/configuration.py", line 480, in get_ossec_conf
wazuh_1          |     xml_data = load_wazuh_xml(conf_file)
wazuh_1          |   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.7-py3.9.egg/wazuh/core/utils.py", line 700, in load_wazuh_xml
wazuh_1          |     with open(xml_path) as f:
wazuh_1          | FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
wazuh_1          | 
wazuh_1          | During handling of the above exception, another exception occurred:
wazuh_1          | 
wazuh_1          | Traceback (most recent call last):
wazuh_1          |   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.7-py3.9.egg/wazuh/core/cluster/utils.py", line 58, in read_cluster_config
wazuh_1          |     config_cluster = get_ossec_conf(section='cluster', conf_file=config_file)['cluster']
wazuh_1          |   File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.7-py3.9.egg/wazuh/core/configuration.py", line 485, in get_ossec_conf
wazuh_1          |     raise WazuhError(1101, extra_message=str(e))
wazuh_1          | wazuh.core.exception.WazuhError: Error 1101 - Requested component does not exist: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
```

When I comment volumes for `local_rules.xml` and `local_decoder.xml`, everything works, this only occurs when I try to import those files.
