### ISSUE TITLE
Agents disconnected - can't reconnect

### ISSUE THREAD

**Issue by mcarden** [wazuh/wazuh-docker#828]
We have a Wazuh 4.2.5 docker single node installation. Recently, around half of the ~60 connected hosts had their agents become disconnected at about the same time for no apparent reason. The agent and server logs are showing 'ERROR: Duplicate agent name' on re-connection attempts.

Using `/var/ossec/bin/manage_agents -r <agent-ID>` to manually remove a disconnected agent via the wazuh-master container on the server DOES result in the agent  being removed from the Wazuh GUI, but it soon returns with a new ID, a state of `Never connected' and the duplicate agent name error continues.

Is there a way to remove these 'duplicates' from the Wazuh server so that they may be added again?

**Comment by davidcr01** [comment]
Hello. 

I was investigating your error, and this behavior was reported in [this](https://github.com/wazuh/wazuh/issues/13580) issue. In that issue, another issue was linked, which reported that the problem was originated because of the `client` block config in [this](https://github.com/wazuh/wazuh/issues/13583) issue.

The following [PR](https://github.com/wazuh/wazuh/pull/13642) was merged into 4.3.3, and you report this behavior in 4.2.5. So the error should be solved in versions higher than the previous mentioned.
