### ISSUE TITLE
Unable to deploy via docker on Raspberry Pi 4 | SSL Certificates

### ISSUE THREAD

**Issue by Cl4r1ty-1** [wazuh/wazuh-docker#895]
I am currently trying to deploy Wazuh via docker on a Raspberry Pi 4, however I cannot due to this error
`pi@rpiserver:~/wazuh-docker/single-node $ docker-compose -f generate-indexer-certs.yml run --rm generator`
`standard_init_linux.go:219: exec user process caused: exec format error` which I am aware means the wrong CPU architecture. I do have certs from Let'sEncrypt on this pi already as there is a web server running (I was planning on changing the dashboard port). Could I continue with the deployment with the current certs or would this not be possible?

**Comment by rauldpm** [comment]
Hello @Cl4r1ty-1, this is an expected error, currently, the wazuh-docker repository does not allow deployment on ARM architectures as no images are available for ARM architecture, this is due to an incompatibility of Filebeat 7.10.2 with ARM.

The issue for the development of ARM components is https://github.com/wazuh/wazuh-packages/issues/1637, once this has been resolved, we will be able to support it in this repository

**Comment by Cl4r1ty-1** [comment]
> Hello @Cl4r1ty-1, this is an expected error, currently, the wazuh-docker repository does not allow deployment on ARM architectures as no images are available for ARM architecture, this is due to an incompatibility of Filebeat 7.10.2 with ARM.
> 
> The issue for the development of ARM components is https://github.com/wazuh/wazuh-packages/issues/1637, once this has been resolved, we will be able to support it in this repository
> 

Thanks, I will try to keep myself updated.
