### ISSUE TITLE
docker-compose error for certificate

### ISSUE THREAD

**Issue by gagestinson** [wazuh/wazuh-docker#928]
When running the `docker-compose -f generate-indexer-certs.yml run --rm generator` as stated on the [Docker Deployment page](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html), I get the following error output and error:

`
[+] Running 1/1
⠿ Network single-node_default  Created                                    0.1s
exec /entrypoint.sh: exec format error
`

Any chance there is a solution? I am running Ubuntu 22.04.3 LTS on an Orange Pi 5 which uses ARM architecture. I am assuming the error is due to the architecture?

**Comment by vcerenu** [comment]
Hello @gagestinson 

The error you are getting is because the Docker image is compiled in amd64.

You can solve this by building your own image, you do this with the following steps:

1 - go to the root of the repository (wazuh-docker)
2 - cd indexer-certs-creator
3 - docker build -t wazuh/wazuh-certs-generator:0.0.1 .

I would like to clarify that the Wazuh Docker images are all compiled in amd64 and currently do not compile with arm64 due to some incompatibilities of the packages used, but we are working to have a release with compilation in arm64 for a future release.

**Comment by gagestinson** [comment]
Unfortunate, alright I guess I will use proxmox on a different system for it. Any chance there is an ETA for the arm configuration?

**Comment by gagestinson** [comment]
Seems I am now getting a different error when running `docker-compose up -d`

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown`

The memory I have allocated is 6.5 GB and 2 CPU cores. I am unsure what resource limits it could be referring to.

**Comment by vcerenu** [comment]
Hello @gagestinson 
We currently do not have an ETA for the ARM version of the images.

About the other error that you have, I recommend that you add some parameters inside the `docker-compose.yml`, in the services that do not have it:

```
    ulimits:
       memlock:
         soft: -1
         hard: -1
       nofile:
         soft: 65536
         hard: 65536
```
