### ISSUE TITLE
Persist the custom logo in the Wazuh dashboard

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-docker#990]
## Description

As reported in https://github.com/wazuh/wazuh-docker/issues/989,  when setting a custom logo the image is not being persisted either. After restart, the text "Menu logo" is shown instead of the selected image.

![2023-09-07_10-48](https://github.com/wazuh/wazuh-docker/assets/7939712/e8a6fffa-b6e9-446e-8e09-6182d20f7d0d)

As of version **4.5.2** this is still happening.

It would be necessary to persist the folder that contains the custom images: `/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom/images/`.

A similar issue is: https://github.com/wazuh/wazuh-docker/issues/951

## Validation

1. Create a single-node environment.
2. Log in to the Wazuh dashboard.
3. Change the custom logo. Related documentation: https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/custom-branding.html
4. Run docker-compose down and then docker-compose up -d.
5. Log in to the Wazuh dashboard again and check if the logo persisted.

**Comment by vcerenu** [comment]
Tried mounting the files directly but they were not taken by `Wazuh dashboard` due to permissions issues
We tried mounting the `/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom` directory directly, but since it did not exist completely, the `custom` directory was created with `root` permissions and this caused `Wazuh dashboard` to not be able to write to it.

In order to mount a Docker volume in that location, the directory had to be added at the time of image creation and given specific permissions, so that when the Docker volume was mounted it would inherit the permissions it already had on the container.

**Comment by vcerenu** [comment]
v4.5.1 deployment:

![image](https://github.com/wazuh/wazuh-docker/assets/56500015/aefe76a5-980e-491d-a581-983e8fe6af6e)
![image](https://github.com/wazuh/wazuh-docker/assets/56500015/8948a4d3-d53b-4a54-9fc5-fd45cf0cf37d)


After v4.5.2 upgrade with new custom persistant volume:

![image](https://github.com/wazuh/wazuh-docker/assets/56500015/ef109888-c3f8-41ad-8b9b-82dd056f3121)
![image](https://github.com/wazuh/wazuh-docker/assets/56500015/0d516076-aae8-45c5-9df0-4540966168ba)
